### ISSUE TITLE
Release and Update details availability on registries and hubs

### ISSUE THREAD

**Issue by gamlab-jlin** [mathworks-ref-arch/matlab-dockerfile#103]
Hi Team,

I was looking for a way to track what are the available latest Update levels and releases on both Docker Hub and for MPM. However, I could not find such information readily available anywhere. 

I have to either try to build with MPM and specify the update levels and test if it is available or Pull the images from Docker Hub and start the image and check its version.

This is quite an overhead just to check what is the current latest update level for certain releases.
Is there a more sophisticated way, that I did not think of?

Thank you in advance,
Jia Lin

**Comment by mw-skardile** [comment]
Hi @gamlab-jlin ,

I understand that checking the list of available update levels can be an overhead with the existing workflow. However, MPM already installs the latest available update for a given release. For example, if you use --release=R2023b, MPM will automatically install the latest available update for R2023b.

If this doesn't meet your requirements, please feel free to visit the [MathWorks Downloads](https://www.mathworks.com/downloads/) page for available releases and updates.

Thank you!

**Comment by gamlab-jlin** [comment]
Hi @mw-skardile,

Thanks for the heads-up. Indeed you are correct, assuming the latest available update is what is being installed with the default release switch, then this information should be clear and cover the issue.

After reconsidering, the main pain of the situation was that there were some issues with the automation for Docker Hub image maintenance. There is no way to specify the Update level for the Docker Hub image as always the latest is available.  The installation was challenging since the interactive image was behind the latest update level.

Overall, I think this would be nice to have, but not critical considering that the intended situation is to **have the same update levels across MPM and DockerHub and Standard installers**. It would be possible to track updates of the version of MPM as well the packages updates (Products and Support Packages) (similarly to Node Package Manager npm). We could use the installer-input files similar to package.json. Then we can be notified if Updates arrive and should consider an Update in the Pipeline environments as well.

Thank you again for your support. Let's close this for now as it is not a critical enhancement.

Thanks,
Lin

**Comment by mw-skardile** [comment]
Hi @gamlab-jlin,

Thank you for clarifying your use case. I'm glad the default MPM behavior currently meets your requirements. If it becomes a pain point, please feel free to reopen this issue.
