### ISSUE TITLE
Private package registries for air-gapped networks

### ISSUE THREAD

**Issue by CiaranMcAndrew1** [mathworks-ref-arch/matlab-dockerfile#105]
_Recognise this is a pretty big request, probably needs raising through the advisory board route too._

Some industries rely on air-gapped networks for security reasons. mpm cannot work in these environments. It would be desirable to be able to self-host a mpm package repository and configure mpm to pull from it.

**Comment by prabhakk-mw** [comment]
Hi @CiaranMcAndrew1 

I'm sure you are already aware of this but `mpm` does provide a `--source` flag whose documentation is:

```markdown
Full path to the installation source. You can specify one of these sources:

Downloaded product files. For more details, see [Download Products Without Installing](https://www.mathworks.com/help/install/ug/download-without-installing.html). (R2018b and later releases)
An ISO or DMG image. You can download images from [MathWorks Downloads](https://www.mathworks.com/downloads). (R2021b and later releases)
If you do not set --source, then mpm downloads the the product files from MathWorks.
```

Is it an acceptable workflow for this environment to download the desired MATLAB ISO's into this air-gapped network and for use with `mpm install --source /path/to/sources ...` these clients?

I realize that this might not be serving the vision you had in mind, and we will reach out to you offline for more information.

Thank you!

**Comment by CiaranMcAndrew1** [comment]
Thank you @prabhakk-mw

I did not catch that detail that mpm can work with an iso file. I was expecting it would need a more substantial package repository. I will test this approach and feedback any successes.
