### ISSUE TITLE
Inconsistent installation directories

### ISSUE THREAD

**Issue by admclrk** [mathworks-ref-arch/matlab-dockerfile#107]
There are several inconsistencies in the installation paths. Here, I am just describing Linux paths, however similar inconsistencies exists for other OSs.
- The default installation path provided by the [GUI installer](https://www.mathworks.com/matlabcentral/answers/1889152-how-do-i-install-matlab-to-a-custom-directory-at-the-root-level-on-linux-systems#answer_1142347) is `usr/local/MATLAB/R2024a`
- The default installation path in the [Dockerfile README](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/README.md) is `/opt/matlab/r2024a`
- The default installation path described in the [Dockerfile](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/dc71095be4c0462428922791044597e1e666542f/Dockerfile#L21) comments is `/opt/matlab/R2024a`
  - Note that the actual installation path matches the README at `/opt/matlab/r2024a`
- The default installation path in the [MPM README](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/MPM.md#product-installation-options) is `/usr/share/matlab`
- The default installation path in the [mpm input file](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/dc71095be4c0462428922791044597e1e666542f/mpm-input-files/R2024a/mpm_input_r2024a.txt#L52) is `/usr/local/R2024a`

**Comment by prabhakk-mw** [comment]
Thank you @admclrk for bringing this to our attention and documenting your research into this issue. 

We work towards bringing consistency into these install locations.

Out of curiosity, how did you stumble onto this?

**Comment by admclrk** [comment]
We're trying to transition our local installations away from the GUI to MPM and I noticed the conflict. We're also using MATLAB on Docker. I flagged the issue to some engineers at MAB last week who suggested that I file a report here. Then I just did my due diligence and searched the docs for other instances of the conflict.

**Comment by admclrk** [comment]
I found [one more](https://www.mathworks.com/help/install/ug/get-mpm-os-command-line.html#mw_5baaf74a-a7ef-4d8f-8615-056cbc5ace65) at `/home/<USER>/matlab`..
