### ISSUE TITLE
latest version of mpm (2024.2) fails on libunwind error on RedHat 8.9

### ISSUE THREAD

**Issue by mattysan** [mathworks-ref-arch/matlab-dockerfile#112]
We are using a RedHat ubi8 (8.9) docker image to install matlab and toolboxes. Our last docker build from two weeks ago ran successfully.  Yesterday I tried re-running that pipeline (we have changed nothing on our end) and now when mpm is executed we see the following error:

[root@f864ceb27d65 ~]# ./mpm --version
/tmp/mwse_3923021466/bin/glnxa64/mpm: error while loading shared libraries: libunwind.so.8: cannot open shared object file: No such file or directory

On an ubuntu image, this works fine and tells me I am running 2024.2

Has mpm had a recent new release in the last 2 weeks? And if so, was it tested with RedHat?

**Comment by mattysan** [comment]
On Ubuntu:
root@a79b67d193db:/# ./mpm --version
MATLAB Package Manager 2024.2 (glnxa64)

**Comment by DmytroMelnyk** [comment]
Steps to reproduce are easy:
```
Invoke-RestMethod https://raw.githubusercontent.com/mathworks-ref-arch/matlab-dockerfile/main/Dockerfile | docker build --build-arg MATLAB_RELEASE='r2019b' -t matlab:r2019b -
```
or linux:
```
curl https://raw.githubusercontent.com/mathworks-ref-arch/matlab-dockerfile/main/Dockerfile | docker build --build-arg MATLAB_RELEASE='r2019b' -t matlab:r2019b -
```

**Comment by sbnicholas** [comment]
We can confirm that MPM 2024.2 (released on Wednesday) has a bug which causes MPM to fail on some Linux distributions. We've identified the cause of the issue and are developing a fix which we plan to release next week.

As a workaround, you can update your Dockerfile (line 58 in the official Dockerfile) to download the previous version of MPM by changing the URL to this:

https://ssd.mathworks.com/supportfiles/downloads/mpm/2024.1.1/glnxa64/mpm
