### ISSUE TITLE
New javascript Desktop can be installed by MPM

### ISSUE THREAD

**Issue by Kubadrew** [mathworks-ref-arch/matlab-dockerfile#119]
Hello Everyone,

I'm using Dockerfile from this repo to build Matlab 2024b container.
By default this container use old Desktop and to switch to new one manual steps using Add-ons was needed.
I'm wondering if it would be possible to install New Desktop using MPM any soon ?

Many Thanks
Jakub

**Comment by prabhakk-mw** [comment]
Hi @Kubadrew 

Could you please clarify which Dockerfile in this repository you are referring to? and also, how you are accessing the MATLAB Desktop, is it via the `-vnc` or the `-browser` flags?

Tagging @michaelmcdonnellmw

**Comment by Kubadrew** [comment]
Hello @prabhakk-mw

I'm referring to https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/Dockerfile

My setup is docker running on WSL. WSLg is used for screen forwarding (more info here: https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)

Thanks
Jakub

**Comment by prabhakk-mw** [comment]
@Kubadrew 
Thank you for clarifying!

@mw-skardile Do you have any thoughts to share on installing Add-Ons from the MathWorks File Exchange through MPM?

In the meantime, @Kubadrew have you considered saving the container after you have installed the Add-On? 
Perhaps this could be a useable workaround in the mean time?

Kindly refer to this [documentation page](https://www.mathworks.com/help/cloudcenter/ug/save-changes-in-containers.html) on saving the container for more information.

Thank you.

**Comment by Kubadrew** [comment]
@prabhakk-mw

Thanks for suggestion, Yes I'm using this workaround for now.

**Comment by prabhakk-mw** [comment]
Hi @Kubadrew , 
We do not have any plans on supporting this capability at this moment.
Hopefully, the suggested workaround suffices until a better alternative is available.
