### ISSUE TITLE
Installing updates as part of the build process

### ISSUE THREAD

**Issue by phrqas** [mathworks-ref-arch/matlab-dockerfile#12]
Great stuff in this project! I follow your README.md instructions to build a custom Docker image with R2019B for use in my organization.

My organization suggests that we install MATLAB using the ISO files and we have a central network license server for authentication. This works fine both for my desktop setup, as well as the Docker. However, one thing that I've been struggling with is installing updates as part of the build process, per the title. On my desktop machine, I can very easily download the latest updates for R2019B following the procedure described at https://www.mathworks.com/help/matlab/matlab_env/check-for-software-updates.html while keeping an active network connection to our license server. Unfortunately, I have not found a way to achieve the same goal in my Docker image. For that reason, my desktop machine runs R2019B Update 5, while my Docker has the baseline R2019B installation from the ISO. Ideally, we would like these two to always be the same.

I tried contacting MathWorks support to ask this question, but kept being told to contact my license administrator to get the update files for R2019B and perform an offline installation. However, an automated option that simply downloads the latest available updates whenever we decide to regenerate the MATLAB Docker image would be strongly preferred, just like we do in our desktop environments. Could that be achieved by adding a couple optional steps to the Dockerfiles?

Thank you very much for your help!

**Comment by josmartin** [comment]
@phrqas If you download the latest ISO from our web site it will always be updated to contain the latest update release. So to ensure that your docker container is running the latest update, just download the ISO (latest!) and run docker build against this repo. Hope that helps.
