### ISSUE TITLE
Usage for Academic License?

### ISSUE THREAD

**Issue by dapperfu** [mathworks-ref-arch/matlab-dockerfile#13]
These licenses are activated by logging in through e-mail & password (and occasionally need to go through a university portal).

From what I can see there is no place to download a 'license file' for use in the instructions.

![Screenshot at 2020-05-19 21-13-19](https://user-images.githubusercontent.com/223258/82394133-30636600-9a16-11ea-84f4-eb7c8466d89b.png)

**Comment by josmartin** [comment]
The expectation for this docker container build is that you have access to a Flex server somewhere on your university network (which is how all our campus wide licenses can work). The administrator of that server (and your university can have many of these servers) will be able to give you a network.lic file - essentially a file that points to that server to allow the MATLAB to check out a license. With that file you should follow the instructions in the docker build process to enable its use in the container.

**Comment by dapperfu** [comment]
To clarify, unless the university already has a Flex server setup this will not be possible? While they 'can' set it up mine does not.
