### ISSUE TITLE
help center can't open

### ISSUE THREAD

**Issue by iowrite** [mathworks-ref-arch/matlab-dockerfile#131]
i use 2024b with docker, when i click help button in main window, nothing happend

**Comment by epaganon** [comment]
Hello @iowrite ,

The "Help" button in the main window opens the online documentation. MathWorks' Docker images come without a pre-installed web browser so, by consequence, the online documentation is not accessible. 

Installing a web browser, e.g. Mozilla Firefox, will resolve the issue.

Please, be aware that if you do not save the docker image after installing the browser, you will have to re-install it every time you start a new container.

**Comment by iowrite** [comment]
@epaganon  thankyou!

**Comment by iowrite** [comment]
matlab@7fe362487803:~/Documents/MATLAB$ sudo apt install firefox
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
firefox is already the newest version (1:1snap1-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
matlab@7fe362487803:~/Documents/MATLAB$ firefox

Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:

snap install firefox

matlab@7fe362487803:~/Documents/MATLAB$ snap install firefox
error: cannot communicate with server: Post "http://localhost/v2/snaps/firefox": dial unix /run/snapd.socket: connect: no such file or directory
＝＝＝＝＝＝＝＝＝
I don't konw how to start snapd daemon in docker

**Comment by epaganon** [comment]
Hello @iowrite ,

Please follow the recommended instructions to install Firefox from Mozilla's official documentation: https://support.mozilla.org/en-US/kb/install-firefox-linux.

I hope that helps.

Thanks

**Comment by iowrite** [comment]
@epaganon  thank for your patient help. firefox was installed successfully. online document is work fine now.
