### ISSUE TITLE
Windows Support.

### ISSUE THREAD

**Issue by dapperfu** [mathworks-ref-arch/matlab-dockerfile#14]
[NXP's Model-Based Design Toolbox](https://www.nxp.com/design/automotive-software-and-tools/model-based-design-toolbox:MC_TOOLBOX) is not available for Linux. 

We would like to containerize the code-generation process to ensure repeatable builds. It also removes needing to know how to use the build process from people doing Simulink modeling.

**Comment by josmartin** [comment]
Thanks for your request - at the moment there are significant technical issues with running MATLAB in windows containers. In particular there are some general properties of windows containers that do not work in the same way to a desktop or server windows OS. We are waiting for Microsoft/docker to fix these issues before we consider releasing windows containers for MATLAB.

**Comment by dmbarry86** [comment]
Hi @josmartin, I was just wondering if there were any recent advances with Windows container support? We've got a usecase where we would like to run MATLAB inside Docker on both Linux and Windows containers.

**Comment by josmartin** [comment]
@dmbarry86  No updates I'm afraid - drop me a line on my work e-mail and we can chat about details.
