### ISSUE TITLE
Unable to connect to the license server. 

### ISSUE THREAD

**Issue by knutj** [mathworks-ref-arch/matlab-dockerfile#15]
When I run the container I get this error message

podman run -it --rm matlab:r2020a
MATLAB is selecting SOFTWARE OPENGL rendering.
License checkout failed.
License Manager Error -96
Unable to connect to the license server. 
Make sure that the client machine can communicate with the hostname listed in the SERVER line of the
license file, and that the port listed in the SERVER line is not blocked by a firewall.

Troubleshoot this issue by visiting: 
https://www.mathworks.com/support/lme/R2020a/96

Diagnostic Information:
Feature: MATLAB 
License path: 27000@knut.localdomain:/home/matlab/.matlab/R2020a_licenses:/usr/local/MATLAB/licenses/license.dat:/
usr/local/MATLAB/licenses 
Licensing error: -96,7. System Error: 2

I have follow the howto but I used podman instead of docker.

**Comment by josmartin** [comment]
@knutj Can you confirm that you are running a FlexLM license server on port 27000 of the machine named  knut.localdomain, and that you have a valid concurrent license on that Flex Server?

**Comment by knutj** [comment]
I am not using a license server.

**Comment by josmartin** [comment]
To use this container you need to be running a network license server somewhere - that is what the LICENSE_SERVER environment variable points to; it is also why you received the error you mention above. This link (https://www.mathworks.com/matlabcentral/answers/105860-how-do-i-install-the-network-license-manager) will help you get a network license manager installed.
