### ISSUE TITLE
docker build error R2020a

### ISSUE THREAD

**Issue by rogelioamancisidor** [mathworks-ref-arch/matlab-dockerfile#16]
I get this error at step 8/19 (I am instaling it in WSL)

    /matlab-install/bin/glnxa64/install_unix: error while loading shared libraries: /matlab- 
    install/bin/glnxa64/libexpat.so.1: file too short
    cat: /tmp/mlinstall.log: No such file or directory

**Comment by josmartin** [comment]
This would suggest that you have perhaps not completely downloaded the installer, or had a failure during unzipping the installer? For completeness I checked what you should be getting for libexpat.so on an R2020a install ...
```
matlab-install/bin/glnxa64$ md5sum libexpat.so.1.6.9
cf30d5ef941d8cced3cc9e7ce80bdcae  libexpat.so.1.6.9
```
Also you could check that you have a valid dynamic library by changing directory to where libexpat.so.1 is found ("GIT repo"/matlab-install/bin/glnxa64) ad executing
```
matlab-install/bin/glnxa64$ ldd libexpat.so.1
        linux-vdso.so.1 (0x00007ffcba9a2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3aa733c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3aa717b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3aa73bd000)
```
These will confirm if you have a valid library - I would expect your md5sum to confirm against the one above if you are installing R2020a.

**Comment by rogelioamancisidor** [comment]
I got the same output values as yours.  I have run the installer couple of times, since I also thought that the file  `libexpat.so.1` is not being unzip correclty, but installer finalize without throwing any error. I see that the size of  `libexpat.so.1` is 0 kb, so the problem is the installer. Is it any other way to install the files? my matlab account does not provide me iso images.

**Comment by josmartin** [comment]
libexpat.so.1 is part of the installer itself - not a result of running the installer. If you have downloaded the install or unzipped it incorrectly then you might get a zero sized libexpat.so.1 - please re-download the iso or the install to ensure that you get a correctly unzipped set of files for install.
