### ISSUE TITLE
Cannot install optional dependencies - sources missing

### ISSUE THREAD

**Issue by dabosch** [mathworks-ref-arch/matlab-dockerfile#17]
Hi,

I'm installing R2020a using the current commit  [65e6291](https://github.com/mathworks-ref-arch/matlab-dockerfile/commit/65e62910270504f64a29574446e7b14e17e27505).
when I decided to install optional dependencies (for example by uncommenting line _71_: `RUN apt-get install -y gcc g++ gfortran`) I got an error, stating that the package was not found. The reason for that is simple: In line _61_ the local package lists are deleted in order to keep the image small. While this makes sense in general, it breaks the following apt-get lines.

I can see two possible solutions:
1) remove line _61_, accepting the fact that some unnecessary data will be included in the final container image
2) change all following (optional) apt-get lines to 
`apt-get update && apt-get install foo bar &&  rm -rf /var/lib/apt/lists/*`

**Comment by josmartin** [comment]
@dabosch Thanks for the suggestions. I've some other relatively minor changes to the Dockerfiles so I'll add in this requested change.
