### ISSUE TITLE
gui

### ISSUE THREAD

**Issue by knutj** [mathworks-ref-arch/matlab-dockerfile#18]
Are there any plant to include gui when running matlab in docker.

**Comment by josmartin** [comment]
Thanks for the suggestion @knutj - we have added desktop-type features to the container that we released into NGC ([see here](https://ngc.nvidia.com/catalog/containers/partners:matlab)) but had expected user of this container to not really need a GUI. We will consider adding an additional Dockerfile that you could build after building the main container that would add a VNC desktop that is available over either VNC or html. Would that work for you?

**Comment by mohsinis** [comment]
@knutj, I added X11 package in my container and I am running below command to get the GUI interface of Matlab.  
```
docker run --name matlab2019a \
        -ti -d \
        -e DISPLAY \
        -e 'QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb' \
        -e USER=\$USER \
        -e HOME=\$HOME \
        -w $HOME \
        -u `id -u`:`id -g` \
        --net=host --pid=host --ipc=host \
        --mount type=bind,src=/var/lib/sss/pipes/,target=/var/lib/sss/pipes \
        --mount type=bind,src=$HOME,target=$HOME \
        --add-host=LicenseServer:10.100.x.x \
        xyz.azurecr.io/matlab2019a:dynare
```

**Comment by josmartin** [comment]
Glad it's working for you. Just to add, you may find that you also need to add

`--shm-size=512M`

as there are some issues with shared memory allocation with docker being very small.
