### ISSUE TITLE
Instructions to use Standalone/Individual license file

### ISSUE THREAD

**Issue by russkel** [mathworks-ref-arch/matlab-dockerfile#19]
Hi,

I have a standalone license.lic file from the Matlab licensing website, could you please modify your README to include instructions on how to use it instead of a network licensing?

Thanks

**Comment by russkel** [comment]
Which, for anyone wondering, you just modify the Dockerfile to ADD `licence.lic` instead of `network.lic`. You will also need to use the `--network host` flag when doing the `docker run`, so MATLAB gets exposed to the actual hardware its licensed to.

**Comment by mohansuresh** [comment]
I am trying to dockerize version R2019b using a network licensing `network.lic`.
But in step 10 of the `Dockerfile.R2019b` I am referring to the below command in line number 146
`# Now install MATLAB
RUN cd /matlab-install \
    && ./install    -mode silent \
                    -inputFile /matlab_installer_input.txt \
                    -licensePath /tmp/network.lic `

I am getting an error like this

````
(Jun 17, 2020 11:59:59) Starting local product/component search in download directory
(Jun 17, 2020 11:59:59) Searching for archives...
(Jun 17, 2020 11:59:59) Reading /matlab-install/archives
(Jun 17, 2020 11:59:59) 2 files found in /matlab-install/archives
(Jun 17, 2020 11:59:59) Reading /matlab-install
(Jun 17, 2020 11:59:59) 16 files found in /matlab-install
(Jun 17, 2020 11:59:59) Archive search complete.  18 total files found.
(Jun 17, 2020 11:59:59) Completed local product/component search
(Jun 17, 2020 11:59:59) Fetching settings
(Jun 17, 2020 12:00:00) No products are selected. The product lines specified in the input file are invalid. Verify the product list and restart the application.
(Jun 17, 2020 12:00:00) Exiting with status -2
(Jun 17, 2020 12:00:00) End - Unsuccessful.
Finished
Removing intermediate container ac86149ef588
 ---> 910c7f92bde1
Step 11/24 : FROM prebuilder
 ---> 2c168b8a5e07
Step 12/24 : COPY --from=middle-stage /usr/local/MATLAB /usr/local/MATLAB
 ---> 4d77f977f982
Step 13/24 : ARG MATLAB_RELEASE
 ---> Running in 88aa433eae82
Removing intermediate container 88aa433eae82
 ---> e7b2f08295bf
Step 14/24 : ADD startmatlab.sh /opt/startscript/
 ---> 5616fb794105
Step 15/24 : RUN chmod +x /opt/startscript/startmatlab.sh &&     ln -s /usr/local/MATLAB/$MATLAB_RELEASE/bin/matlab /usr/local/bin/matlab
 ---> Running in 876a8a93fc6a
Removing intermediate container 876a8a93fc6a
 ---> eb61ab995c8b
Step 16/24 : ENV MATLAB_RELEASE $MATLAB_RELEASE
 ---> Running in fd33598ea7a6
Removing intermediate container fd33598ea7a6
 ---> 2d9e3b40f923
````

In the `Dockerfile.R2019b` :-
- I have commented `ENV MLM_LICENSE_FILE` in line number 182.
- I have uncommented `ADD network.lic /usr/local/MATLAB/$MATLAB_RELEASE/licenses/` in line number 187.

In `matlab_installer_input.txt`:-
- I have uncommented `fileInstallationKey` in line number 53 and added a valid installation key.
- I have uncommented `agreeToLicense` in line number 67 and added the value `yes`.
- I have uncommented `product.MATLAB` in line number 283.

Does anyone have a suggestion here?
I am using Docker for windows with linux containers.
I am behind a corporate proxy. So I ran the build command with `docker build --no-cache --network host -f Dockerfile.R2019b -t matlab:r2019b --build-arg MATLAB_RELEASE=R2019b .`

It says `No products are selected. The product lines specified in the input file are invalid. Verify the product list and restart the application.` but my installation key and network.lic is 100% correct.

Am I missing something??

Please help.

Thanks

**Comment by josmartin** [comment]
@mohansuresh I'll deal with your question in issue #20 - OK

**Comment by mohsinis** [comment]
@mohansuresh, I had similar issue, when I was uncommenting the products. 
If you keep the products commented and run the build again it will resolve and install all the licensed matlab products automatically.
