### ISSUE TITLE
COPY failed

### ISSUE THREAD

**Issue by catanto** [mathworks-ref-arch/matlab-dockerfile#2]
Hi, 

I'm trying to install Matlab on Docker and I followed all the procedure but, when I try to build the image, I get this error: 

Step 10/22 : COPY --from=middle-stage /usr/local/MATLAB /usr/local/MATLAB
COPY failed: stat /var/lib/docker/overlay2/ba4ffcd0bcd44f47cb4f904c2b6e5bf109a1a16b9ec5ab502e0748ff2c4042a8/merged/usr/local/MATLAB: no such file or directory

What can I do to fix it? Thank you for helping me

**Comment by josmartin** [comment]
If the `COPY `from `middle-stage` failed then the MATLAB install in the middle stage didn't complete correctly. You should look earlier in the docker build output to see why the following line didn't install MATLAB in the `middle-stage`.

```
RUN cd /matlab-install \
    && ./install -mode silent -inputFile /matlab_installer_input.txt
```
This will output all the text from the installer in the docker build output and will indicate what didn't work.
