### ISSUE TITLE
Could not Use a License File to Build Image

### ISSUE THREAD

**Issue by mohansuresh** [mathworks-ref-arch/matlab-dockerfile#20]
I am trying to dockerize version R2019b using a network licensing `network.lic`.
But in step 10 of the `Dockerfile.R2019b` I am referring to the below command in line number 146
`# Now install MATLAB
RUN cd /matlab-install \
    && ./install    -mode silent \
                    -inputFile /matlab_installer_input.txt \
                    -licensePath /tmp/network.lic `

I am getting an error like this

````
(Jun 17, 2020 11:59:59) Starting local product/component search in download directory
(Jun 17, 2020 11:59:59) Searching for archives...
(Jun 17, 2020 11:59:59) Reading /matlab-install/archives
(Jun 17, 2020 11:59:59) 2 files found in /matlab-install/archives
(Jun 17, 2020 11:59:59) Reading /matlab-install
(Jun 17, 2020 11:59:59) 16 files found in /matlab-install
(Jun 17, 2020 11:59:59) Archive search complete.  18 total files found.
(Jun 17, 2020 11:59:59) Completed local product/component search
(Jun 17, 2020 11:59:59) Fetching settings
(Jun 17, 2020 12:00:00) No products are selected. The product lines specified in the input file are invalid. Verify the product list and restart the application.
(Jun 17, 2020 12:00:00) Exiting with status -2
(Jun 17, 2020 12:00:00) End - Unsuccessful.
Finished
Removing intermediate container ac86149ef588
 ---> 910c7f92bde1
Step 11/24 : FROM prebuilder
 ---> 2c168b8a5e07
Step 12/24 : COPY --from=middle-stage /usr/local/MATLAB /usr/local/MATLAB
 ---> 4d77f977f982
Step 13/24 : ARG MATLAB_RELEASE
 ---> Running in 88aa433eae82
Removing intermediate container 88aa433eae82
 ---> e7b2f08295bf
Step 14/24 : ADD startmatlab.sh /opt/startscript/
 ---> 5616fb794105
Step 15/24 : RUN chmod +x /opt/startscript/startmatlab.sh &&     ln -s /usr/local/MATLAB/$MATLAB_RELEASE/bin/matlab /usr/local/bin/matlab
 ---> Running in 876a8a93fc6a
Removing intermediate container 876a8a93fc6a
 ---> eb61ab995c8b
Step 16/24 : ENV MATLAB_RELEASE $MATLAB_RELEASE
 ---> Running in fd33598ea7a6
Removing intermediate container fd33598ea7a6
 ---> 2d9e3b40f923
````

In the `Dockerfile.R2019b` :-
- I have commented `ENV MLM_LICENSE_FILE` in line number 182.
- I have uncommented `ADD network.lic /usr/local/MATLAB/$MATLAB_RELEASE/licenses/` in line number 187.

In `matlab_installer_input.txt`:-
- I have uncommented `fileInstallationKey` in line number 53 and added a valid installation key.
- I have uncommented `agreeToLicense` in line number 67 and added the value `yes`.
- I have uncommented `product.MATLAB` in line number 283.

Does anyone have a suggestion here?
I am using Docker for windows with linux containers.
I am behind a corporate proxy. So I ran the build command with `docker build --no-cache --network host -f Dockerfile.R2019b -t matlab:r2019b --build-arg MATLAB_RELEASE=R2019b .`

It says `No products are selected. The product lines specified in the input file are invalid. Verify the product list and restart the application.` but my installation key and network.lic is 100% correct.

One more update: the license server mentioned in `network.lic` is inside my corporate network. I am having access to that server. (I am able to telnet with the host and port mentioned in `network.lic`)

Am I missing something??

Please help.

Thanks

**Comment by josmartin** [comment]
@mohansuresh Could you please post the whole of the docker build output from the beginning, along with the matlab_installer_input.txt (WITHOUT YOUR FIK IN IT!) and your modified Dockerfile so I can see what you are running from.

**Comment by mohansuresh** [comment]
@josmartin,
Thanks for your reply. 

Please find the Dockerfile (added .txt at the end) [Dockerfile.R2019b.txt](https://github.com/mathworks-ref-arch/matlab-dockerfile/files/4796388/Dockerfile.R2019b.txt) and the build output file (replaced FIK with "xxxxx-xxxxx-xxxxx-xxxxx") [output.txt](https://github.com/mathworks-ref-arch/matlab-dockerfile/files/4796406/output.txt) here.

**Comment by josmartin** [comment]
@mohansuresh I believe you haven't correctly downloaded the MATLAB install (step 2 in the top level doc for the repo, and pointing to this [documentation page](https://uk.mathworks.com/help/install/ug/download-without-installing.html)). My reasoning is as follows - I used exactly your Dockerfile as posted above with the same installer input file you had (since that is printed out in the docker build output), with a FIK for just the MATLAB product and got a successful install. However, in looking over my log output as compared to your posted one I noted the following towards the end of the MATLAB install.

```
(Jun 18, 2020 08:14:06) Reading /matlab-install/archives
(Jun 18, 2020 08:14:06) 3324 files found in /matlab-install/archives
(Jun 18, 2020 08:14:06) Reading /matlab-install
(Jun 18, 2020 08:14:06) 18 files found in /matlab-install
(Jun 18, 2020 08:14:06) Archive search complete.  3342 total files found.
(Jun 18, 2020 08:14:06) Fetching settings
(Jun 18, 2020 08:14:07) Fetching settings
(Jun 18, 2020 08:14:07) Assembling product list...
(Jun 18, 2020 08:14:07) Completed local product/component search
(Jun 18, 2020 08:14:08) Download thread pool size = 4
(Jun 18, 2020 08:14:08) Installing Product: MATLAB
(Jun 18, 2020 08:14:51) Notes:

(Jun 18, 2020 08:14:51) Exiting with status 0
(Jun 18, 2020 08:14:51) End - Successful.
```

Note the line that says `3324 total files found`? In your log this says `18 total files found`. I know there are more than 18 files in just a MATLAB install (there should be at least 3324 in an R2019b install since the one I'm running is minimal). 

I believe you should go back and make sure that you have correctly downloaded the install for the matlab product suitable for off-line install.
