### ISSUE TITLE
How to set up a matlab license server?

### ISSUE THREAD

**Issue by YuanGao-NAU** [mathworks-ref-arch/matlab-dockerfile#21]
Hi there,

I tried to build a matlab docker image by following the steps. However, in the step 5:

`docker build -t matlab:r2020a --build-arg LICENSE_SERVER=27000@MyServerName .`

I don't know where's my license server.

I just use the command:

`ecopad@Precision-Tower-5810:~$ docker build -t matlab:r2020a --build-arg LICENSE_SERVER=27000@Precision-Tower-5810 .`

The build was successful, but I can't launch the docker container:

`docker run -it --rm matlab:r2020a -r "disp('hello world');exit"`

The output I got was:
```
ecopad@Precision-Tower-5810:~$ docker run -it --rm matlab:r2020a -r "disp('hello world');exit"
MATLAB is selecting SOFTWARE OPENGL rendering.
License checkout failed.
License Manager Error -96
Unable to connect to the license server.
Make sure that the client machine can communicate with the hostname listed in the SERVER line of the
license file, and that the port listed in the SERVER line is not blocked by a firewall.

Troubleshoot this issue by visiting:
https://www.mathworks.com/support/lme/R2020a/96

Diagnostic Information:
Feature: MATLAB
License path: 27000@Precision-Tower-5810:/home/matlab/.matlab/R2020a_licenses:/usr/local/MATLAB/licenses/license.d
at:/usr/local/MATLAB/licenses
Licensing error: -96,7. System Error: 2
```

Looking forward to your reply!

**Comment by josmartin** [comment]
You should contact the person who administers your license and ask them where they are running the Flex License Server for your organization. It is the hostname for that machine (which holds your license) that you need to bind into the container.

**Comment by YuanGao-NAU** [comment]
Thank you so much!
