### ISSUE TITLE
Using Matlab on Kubeflow

### ISSUE THREAD

**Issue by lalithvaka** [mathworks-ref-arch/matlab-dockerfile#23]
Hi we are trying to enable matlab on our Kubeflow environment with Kubernetes and Nvidia DGX nodes as worker nodes for the GPU processing. I am not sure if am doing this right. 
Attaching the Dockerfile here for your reference. Using the matlab image posted from Nvidia Docker repo. 
[Dockerfile.txt](https://github.com/mathworks-ref-arch/matlab-dockerfile/files/5053631/Dockerfile.txt)

I have added the license server info in the ENTRYPOINT section. 

Please let me know if this is the right way to use Matlab on Kubernetes with GPU worker nodes with Kubeflow as the platform on top?

**Comment by josmartin** [comment]
@lalithvaka I can't comment on your integration into Kubeflow but I assume you know more about this than I do. On the licensing front assuming that the machine you point to in the MLM_LICENSE_FILE environment variable is a valid FlexLM server then I would expect this to work as you describe.
