### ISSUE TITLE
License issue when running the image

### ISSUE THREAD

**Issue by jsalaun** [mathworks-ref-arch/matlab-dockerfile#24]
Hi! I followed the instructions in the readme (here is the content of my [matlab_installler_input.txt](https://hastebin.com/yojakisezi.shell)) and managed to build an image with: 
`docker build -f Dockerfile.R2019b -t matlab:r2019b 
--build-arg MATLAB_RELEASE=R2019b --build-arg LICENSE_SERVER=27000@MY_SERVER .` 
but when attempting to run the container with: 
`docker run-it  --rm --env LICENSE_SERVER=27000@MY_SERVER matlab:r2019b` 
the output I got was: 
```

MATLAB is selecting SOFTWARE OPENGL rendering.
License checkout failed.
License Manager Error -15
Unable to connect to the license server.
Check that the network license manager has been started, and that the client machine can communicate
with the license server.

Troubleshoot this issue by visiting:
https://www.mathworks.com/support/lme/R2019b/15

Diagnostic Information:
Feature: MATLAB
License path: 27000@MY_SERVER:/home/matlab/.matlab/R2019b_licenses:/usr/local/MATLAB/R2019b/licenses/license.dat:/us
r/local/MATLAB/R2019b/licenses/network.lic
Licensing error: -15,570. System Error: 115
```

I am able to ping the server, the network.lic file looks fine and my system administrator tells me everything seems hunky dory on the firewall side.

**Comment by josmartin** [comment]
@jsalaun Can I assume that in the `docker build` command you replaced `LICENSE_SERVER=27000@MY_SERVER` with `LICENSE_SERVER=PORT_FOR_YOUR_ACTUAL_LICENSE_SERVER@THE_FQDN_OF_YOUR_LICENSE_SERVER`? The error you are getting is simply that the MATLAB process you are starting cannot connect to your licenses server either because it is NOT set correctly or that there is some networking issue that precludes connecting to the system.

**Comment by jsalaun** [comment]
> Can I assume that in the docker build command you replaced LICENSE_SERVER=27000@MY_SERVER with LICENSE_SERVER=PORT_FOR_YOUR_ACTUAL_LICENSE_SERVER@THE_FQDN_OF_YOUR_LICENSE_SERVER?

Yes I have.

**Comment by josmartin** [comment]
@jsalaun Then you will need to debug why that docker container cannot correctly contact your license server. I generally recommend doing the following (I'm going to assume that the name of your docker image is `matlab:r2020a` and that your license server is located at port 27000 on machine mylicenseserver.mydomain.com):

1. Start your docker container but run `/bin/bash` instead - `docker run -it --rm --entrypoint=/bin/bash matlab:r2020a`
2. This should leave you at a bash shell prompt inside the container where you can do the following
```
sudo -i
apt-get update
apt-get install netcat
nc -vz mylicenseserver.mydomain.com 27000
```
If you can correctly send a SYN packet (the beginnings of a TCP/IP conversation to port 27000 on your license service then the above will return something like 

`mylicenseserver.mydomain.com [some dotted quad] 27000 (?) open`

This proves that your docker container can actually contact your license server. You can also check to see if you can contact the open internet with something like
```
nc -vz www.google.com 80
```
Given what you are seeing I expect that netcat will not beable to contact your licenses server and that there is some configuration of docker or something else that requires attention.

**Comment by josmartin** [comment]
BTW - @jsalaun Just to be clear - in the output that you posted that you saw the following 
```
License path: 27000@MY_SERVER:/home/matlab/.matlab/R2019b_licenses:/usr/local/MATLAB/R2019b/licenses/license.dat:/us
r/local/MATLAB/R2019b/licenses/network.lic
Licensing error: -15,570. System Error: 115
```
For now I'll assume that you have actually altered this output from what was produced by MATLAB since it contains the string `27000@MY_SERVER` which would not be there if you had correctly defined the build argument during `docker build`.

**Comment by jsalaun** [comment]
> For now I'll assume that you have actually altered this output from what was produced by MATLAB since it contains the string 27000@MY_SERVER which would not be there if you had correctly defined the build argument during docker build.

Yes, I did alter it. Here is the output of the netcat command with only the IP address
```
root@f29d295d133d:~# nc -vz do-eng1 27000
Warning: inverse host lookup failed for XXX.XXX.XXX.XXX: No address associated with name
do-eng1 [XXX.XXX.XXX.XXX] 27000 (?) : Connection refused
```
I am not sure whether this is a configuration or a firewall issue. Also, I am connected to the network through a VPN.

**Comment by josmartin** [comment]
@jsalaun Looks like your License Server host `do-eng1` appears to be rejecting network traffic from your docker container. You and your network administrator should look at the firewall rules between the container and your server. Something appears to be rejecting the connection request for the TCP/IP socket. This is a fundamental piece of networking. Once you get the above netcat to connect I would expect MATLAB to then work with your license server.
