### ISSUE TITLE
Unable to locate the required files during docker build

### ISSUE THREAD

**Issue by tclose** [mathworks-ref-arch/matlab-dockerfile#25]
Hi,

I am trying to follow the installation instructions but not sure what I am doing wrong. The following is the directory structure of the repo

```
$ tree -L 2
.
├── Dockerfile
├── Dockerfile.R2019b
├── LICENSE.md
├── README.md
├── SECURITY.md
├── file-installation-key.txt
├── license.lic
├── matlab-install
│   ├── VersionInfo.xml
│   ├── archives
│   ├── bin
│   ├── cefclient
│   ├── help
│   ├── install
│   ├── installer_input.txt
│   ├── java
│   ├── license_agreement.txt
│   ├── mathworks_installation_help.pdf
│   ├── mathworks_installation_help_es.pdf
│   ├── mathworks_installation_help_ja_JP.pdf
│   ├── mathworks_installation_help_ko_KR.pdf
│   ├── mathworks_installation_help_zh_CN.pdf
│   ├── patents.txt
│   ├── readme.txt
│   ├── resources
│   ├── sys
│   ├── trademarks.txt
│   └── ui
├── matlab_installer_input.txt
└── startmatlab.sh
```

but I am getting the following error
```

(Sep 10, 2020 06:48:25) Reading from /matlab-install/archives
(Sep 10, 2020 06:48:25) Starting local product/component search in download directory
(Sep 10, 2020 06:48:25) Searching for archives...
(Sep 10, 2020 06:48:25) Reading /matlab-install/archives
(Sep 10, 2020 06:48:25) 2 files found in /matlab-install/archives
(Sep 10, 2020 06:48:25) Archive search complete.  2 total files found.
(Sep 10, 2020 06:48:25) Completed local product/component search
(Sep 10, 2020 06:48:25) Finished reading from/matlab-install/archives
(Sep 10, 2020 06:48:25) Missing Installation Files: Unable to locate the required files.

To use a File Installation Key, you must run the installer from a directory that contains the installation files.

For information on how to get the files, see this MATLAB Answer.
	at com.mathworks.install_core_common.MATLABInstallerExceptionUtil.getApplicationException(MATLABInstallerExceptionUtil.java:16)
	at com.mathworks.matlab_installer.services.MatlabInstallerServices.checkArchives(Unknown Source)
	at com.mathworks.installservicehandler.context.ExceptionInterceptor.invoke(ExceptionInterceptor.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.mathworks.installservicehandler.JsonPassThroughResponseWrapper.getData(JsonPassThroughResponseWrapper.java:24)
	at com.mathworks.installservicehandler.JsonPassThroughResponseWrapper.getData(JsonPassThroughResponseWrapper.java:10)
	at com.mathworks.installservicehandler.InstallServiceHandlerClient.executeService(InstallServiceHandlerClient.java:18)
	at com.mathworks.matlab_installer.MatlabInstallerClient$3.executeService(Unknown Source)
	at com.mathworks.installjscommon.InstallerClientUtility.executeGetNextStateInSequence(Unknown Source)
	at com.mathworks.matlab_installer.MatlabInstallerClient.clientMain(Unknown Source)
Caused by: java.lang.Exception: Installer Error: Unable to locate required installation files
	... 13 more

(Sep 10, 2020 06:48:25) Exiting with status -2
(Sep 10, 2020 06:48:25) End - Unsuccessful
The command '/bin/sh -c cd /matlab-install &&     chmod +x ./install &&     ./install -mode silent         -inputFile /matlab_installer_input.txt         -outputFile /tmp/mlinstall.log         -destinationFolder /usr/local/MATLAB     ; EXIT=$? && cat /tmp/mlinstall.log && test $EXIT -eq 0' returned a non-zero code: 1
```

Which installation files am I missing?

**Comment by josmartin** [comment]
@tclose `(Sep 10, 2020 06:48:25) Archive search complete.  2 total files found.` indicates that you have only downloaded the MATLAB installer into the `matlab-install` location. This is not enough I'm afraid. You need to undertake a silent install which requires that you either follow the steps on [this link](https://uk.mathworks.com/help/install/ug/download-without-installing.html;jsessionid=6f18357cb3d797e0b567de35f7c3), or you download the full ISO of all the products. When you complete either of these steps you will end up with a line in your output that says something like `Archive search complete.  NNN total files found.` where NNN is significantly larger than 2.

**Comment by tclose** [comment]
Thanks @josmartin, I haven't had the chance to check this out but it sounds right

**Comment by MaKaNu** [comment]
I stranded on the same issue since the linked downloadpage doesn't provide the isos at the moment (or I simply couldn't find them and I looked twice). Just downloading the files isn't possible because a gui is involved. Thankfully I have some linux-iso laying around. This issue should be reopened since the documentation lets headless guys helpless behind.

**Comment by josmartin** [comment]
Just in case anyone ends up here and can't find the link to download the latest ISO's from the [downloads page](https://www.mathworks.com/downloads/web_downloads/)  pictured below click the latest release to download

![Screenshot 2021-03-04 174652](https://user-images.githubusercontent.com/6057856/110006516-ae78cb00-7d11-11eb-9af6-eb8effc3128f.png)

That should take you to a page somewhat like the picture below (after checking you are logged into your MathWorks account)

![Screenshot 2021-03-04 174519](https://user-images.githubusercontent.com/6057856/110006351-71acd400-7d11-11eb-8e30-291e45a704f1.png)

On this page you want to use the link I've highlighted under the Related Links - this will allow you to download the current ISO. If you want older ISO's you should select 'Click here to download any MathWorks release' on the first page, select the release you are interested in, and finally under Related Links there will be an ISO link.

**Comment by MaKaNu** [comment]
This is actually sadly just true for mathworks admin accounts. I also struggled with the ISO, which we had on our server. At the end I used mobaxterm to download the files via Xforwarding. This is not very straight forward and just a workaround for the real problem.
