### ISSUE TITLE
What is a license server, and do I need one to use this repo?

### ISSUE THREAD

**Issue by roballsopp** [mathworks-ref-arch/matlab-dockerfile#26]
I'd love to use this repo to build an image to compile my matlab code in, but I see it requires a license server of some kind. My organization has probably 10 people using matlab, but no one seems to know anything about a license server. Is there a way to use this image without this server? Is this something someone would definitely have set up if we have multiple people using matlab?

**Comment by josmartin** [comment]
@roballsopp Apologies for the delay in getting back to you. At the moment the only way to license a Continuous Integration type use of MATLAB in a docker container (as I believe you are asking about) is by running a [network license manager](https://uk.mathworks.com/help/install/administer-network-licenses.html). We realise this isn't ideal in many situations and are investigating how to alleviate this in the future.
