### ISSUE TITLE
No matlab-installer-input.txt

### ISSUE THREAD

**Issue by pcamach2** [mathworks-ref-arch/matlab-dockerfile#27]
I'm following the readme tutorial, but there is no matlab-install directory in this repo. I made one and pushed the files I had from mathworks to this directory, but the build fails as such:

```
Step 4/19 : WORKDIR /root
 ---> Running in b9723ad72d85
Removing intermediate container b9723ad72d85
 ---> 03c91319e56b
Step 5/19 : FROM prebuilder as middle-stage
 ---> 03c91319e56b
Step 6/19 : ADD matlab-install /matlab-install/
 ---> 2633844373a8
Step 7/19 : ADD matlab_installer_input.txt /matlab_installer_input.txt
ADD failed: stat /srv/docker/tmp/docker-builder617063380/matlab_installer_input.txt: no such file or directory
```

Is there another repo I need to pull the matlab-install directory from? Thanks in advance for your help!

**Comment by josmartin** [comment]
@pcamach2 You will need to undertake:

**Step 2** in the readme intro to this repo - that is undertake a full download of the software you need to get into the container. You can either follow the "MATLAB Installation Files" part in which you download on linux the installer and then run it and follow the "Download Products Without Installation" path, or you can download the full product ISO which is fairly large. Either of these approaches result in the full set of files that should reside in the `matlab-install` folder of the repo.

**Step 4** in which you create the correct `matlab_installer_input.txt` file which contains the products you want to install, your File Installation Key (FIK) which you acquire in Step 3, and a few other parameters.

If you do the above 2 steps correctly then your `docker build` will succeed. Hope that helps.

**Comment by pcamach2** [comment]
Thanks for the clarification, @josmartin!
