### ISSUE TITLE
May Example for MyServerName

### ISSUE THREAD

**Issue by xinqin23** [mathworks-ref-arch/matlab-dockerfile#28]
Hi! I looked at the file license.lic and tried to create network.lic from the .dat file in folder ..../etc/    

But for the case to link Matlab to docker using:
docker build -t matlab:r2020a --build-arg LICENSE_SERVER=27000@MyServerName .

May I consult what format and how long normally the MyServerName variable looks like? 

Thank you!

Best Regards,
Xin

**Comment by josmartin** [comment]
@xinqin23 The value of the `LICENSE_SERVER` variable should be of the form `port_number@hostname`. In the example case you show the port number is 27000 (this is the default FlexLM port number) for a machine with a short hostname of MyServerName. If you were running the FlexLM server on the machine called `license.server.example.com` at port 27000 you would specify `27000@license.server.example.com`

Hope that helps

**Comment by xinqin23** [comment]
Hi @josmartin !  Thank you so much for the example!!
I am waiting for the reply from our institute for the hostname of our education Matlab

....  trying to activate Matlab inside docker now

May I bravely consult would it possible to have a working hostname to try on  ...

Thank you for reading！

**Comment by josmartin** [comment]
@xinqin23 Given you are at an academic institution you are more likely to want to use this container (https://ngc.nvidia.com/catalog/containers/partners:matlab) which you can get pre-build using
```
docker pull nvcr.io/partners/matlab:r2020b
```
The advantage for you will be that this container will likely allow you to use your MathWorks Account to acquire a license.

**Comment by xinqin23** [comment]
@josmartin I see I see thank you!
