### ISSUE TITLE
Docker build runs out of space

### ISSUE THREAD

**Issue by blankered** [mathworks-ref-arch/matlab-dockerfile#30]
I am attempting to build in a preset container using the following commands:

sudo docker run --name mac5678deb06b61 --mac-address="56:78:de:b0:6b:61" -d ubuntu tail -f /dev/null c3579e4685933b757f51c5f9e357656be3a62abd0e0d6a421b5f1c04045061c

docker build --network container:mac5678deb06b61 --no-cache .

but I run into issues with the installation of matlab running out of space.

(Mar 04, 2021 19:50:44) Exiting with status 0
(Mar 04, 2021 19:50:44) End - Successful
Removing intermediate container 462b17fa24a0
 ---> 21004401b925
Step 13/24 : FROM prebuilder
 ---> 1e38a6d6c3a6
Step 14/24 : COPY --from=middle-stage /usr/local/MATLAB /usr/local/MATLAB
Error processing tar file(exit status 1): write /usr/local/MATLAB/java/jarext/jogl-all.jar: no space left on device

Here are the results of the: sudo docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          3         1         14.26GB   14.19GB (99%)
Containers      1         1         0B        0B
Local Volumes   0         0         0B        0B
Build Cache     0         0         0B        0B

I am new to docker so I am unsure if I need to adjust the size of the container some how or change a configuration to allow for a bigger container.

**Comment by josmartin** [comment]
@blankered "no space left on device" means that your local disk has run out of space (or possibly you have configured docker with a storage-driver of type "devicemapper"). Firstly I would (on your host) execute "df -h /" to see how much free space you have on your disk (docker will usually use space in `/var/lib/docker` with most of the space in `overlay` or `overlay2`). If this is showing a small number (less than 60GB?) you need to free up space somewhere.

**Comment by blankered** [comment]
I had to move the docker storage to a different partition to allow for more space. Thanks for the help!
