### ISSUE TITLE
Can't find the file "installer_input.txt" in my files from r14 iso

### ISSUE THREAD

**Issue by Danielgb23** [mathworks-ref-arch/matlab-dockerfile#34]
I have a r14 matlab unix iso from my college and after extracted I can't find the file you are supposed to copy, the installer_input.txt file. Does this work for this version? It's pretty old.

**Comment by josmartin** [comment]
@Danielgb23 I honestly don't know if you could even get an R14 version of MATLAB from 2004'ish to work in a container - I do know you will have a fair amount of difficulty getting it to match with more recent glibc versions in whatever base OS you have (and have in the container). I would strongly recommend using a more recent copy of MATLAB.
