### ISSUE TITLE
failed: stat usr/local/MATLAB: file does not exist

### ISSUE THREAD

**Issue by nagiosleaner** [mathworks-ref-arch/matlab-dockerfile#35]
Hi, When I build my matlab2021b images , an error was appeared：
![image](https://user-images.githubusercontent.com/9432108/134801934-aa448f30-6811-4068-96eb-de366053c09e.png)

and Could you help me to solve it?

**Comment by josmartin** [comment]
@nagiosleaner It would appear that the installer is unable to find any of the product files that you downloaded in Step 2 of the instructions. Could you confirm that you have downloaded the off-line product installs as outlined in Step 2 and that they are in the folder `matlab-install` alongside the `Dockerfile` and that in that folder there is a file called `install`.
