### ISSUE TITLE
Code compatibility over Matlab on docker

### ISSUE THREAD

**Issue by sfl0r3nz05** [mathworks-ref-arch/matlab-dockerfile#41]
Hi all,

Thanks to issue #40 I could install Simulink on Docker Matlab.

As you can see below I am able to import a project into Simulink:
![1](https://user-images.githubusercontent.com/6643905/144619329-26801a14-7f64-46d9-8f5f-720057c579b3.PNG)

However, when I compile the code with `mex` I am getting several errors. E.g:
![2](https://user-images.githubusercontent.com/6643905/144619666-51153996-7921-4377-8f50-4d4406ab01be.PNG)

As the original project has been created in Matlab Simulink on windows, so the code has been compiled with a Visual Studio compiler instead of gcc, and it works correctly. 

I have doubts if there would be any library or method to make the projects compatible with Matlab Simulink on docker.

Thanks in advance.

**Comment by josmartin** [comment]
@sfl0r3nz05 Could you [contact our normal support](https://www.mathworks.com/support/contact_us.html) and create a service request for this issue - now that the docker container is running correctly this will be more easily routed the right team using our standard channels.
