### ISSUE TITLE
Cannot start X session after having used VNC

### ISSUE THREAD

**Issue by GuzTech** [mathworks-ref-arch/matlab-dockerfile#44]
Hello,

I have followed the instructions on the [MATLAB docker hub](https://hub.docker.com/r/mathworks/matlab) and pulled MATLAB r2021b successfully. I can use it with an X session which works just fine.
Since I need to install several toolboxes, I followed [this guide](https://nl.mathworks.com/matlabcentral/answers/1450174-how-do-i-install-matlab-updates-toolboxes-and-add-ons-in-the-matlab-docker-container) which requires using a VNC session. After installing all the toolboxes I created a new commit without shutting down the docker image. After the commit I shut down the container using `docker stop <container>`.

However, now I am not able to start MATLAB using an X session anymore as it always defaults to using VNC, even without the `-vnc` option when starting the container. It looks like the VNC option is also committed and I cannot figure out how to "unset" this.

EDIT:
I noticed that whenever I run docker without the `-vnc` option, `docker ps` still reports the command as `/bin/run.sh -vnc`. So this option seems "stuck".

**Comment by GuzTech** [comment]
I have worked around this problem by creating a `Dockerfile` with the contents:

```
FROM fullmatlab:r2021b

CMD ["matlab"]
```

where `fullmatlab:r2021b` is the committed container I mentioned in the OP. Then I built a new container:

```
docker build -t matlabwithtoolboxes .
```

So now I just run:

```
docker run -it --rm -e MLM_LICENSE_FILE=27000@licenseserver -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro --shm-size=512M matlabwithtoolboxes
```

---

I am leaving this issue open because the behavior in the OP is not resolved, but I just wanted to post a workaround for people that run into the same problem.

**Comment by JSStabl** [comment]
I get: pull access denied for fullmatlab, repository does not exist or may require 'docker login': denied: requested access to the resource is denied, any ideas how to solve that?

**Comment by josmartin** [comment]
@JSStabl - The container `fullmatlab:r2021b` referred to by @GuzTech only exists on their machine - it is NOT something that has been pushed to dockerhub (which is why you can't pull it). It was made using the instructions above.

**Comment by prabhakk-mw** [comment]
Dear @GuzTech 

One can update the `entrypoint` used during the commit operation using the `--change` flag as described in the documentation for [docker commit](https://docs.docker.com/engine/reference/commandline/commit/)

So, when you create the commit after you install the toolboxes you could use the following syntax:
```bash
$ docker commit --change 'ENTRYPOINT ["/bin/run.sh"]' 35674d1376f0 matlabwithtoolboxes:r2021b
```

In the command above, please replace `35674d1376f0` with the CONTAINER ID of the container that you want to commit.

This should reset the newly created image to have the additional toolboxes that you have already installed using the VNC option while resetting the container to its original state.

For example, I can now run this container with a `-browser` flag as shown below:

```bash
$ docker run -it --rm --init --shm-size=512M -p 8888:8888 matlabwithtoolboxes:r2021b -browser
----------------------------------------------------
Welcome to the MATLAB Container

This container includes commercial software products of The MathWorks,
Inc. ("MathWorks Programs") and related materials. MathWorks Programs are
licensed under the MathWorks Software License Agreement, available in the
MATLAB installation in this container. Related materials in this
container are licensed under separate licenses which can be found in
their respective folders.

Use the -help flag to learn more about the usage of this container:

    docker run mathworks/matlab:r2021b -help

To access MATLAB running in the container via web browser, make sure you have exposed port 8888.
To get started:

    Point a browser to port 8888 of the docker host machine running
    this container

    http://hostname:8888/index.html

If want to launch MATLAB on a different base url, you need to set MWI_BASE_URL environment variable. 
`MWI_BASE_URL`: Default value is '/'. The url at which MATLAB will be accessible at. 
                Must start with '/'. If set to "/matlab", the url to access MATLAB would be:
                `http://hostname:8888/matlab/index.html`

For a complete list of environment variables, check the link below:
https://github.com/mathworks/matlab-proxy/blob/main/Advanced-Usage.md

If you require assistance or have a request for additional features or capabilities, please contact MathWorks Technical Support: https://www.mathworks.com/support/contact_us.html
----------------------------------------------------
INFO:MATLABProxyApp:
==============================================================================================================================
                                                  MATLAB can be accessed at:                                                  
                                                     http://0.0.0.0:8888                                                      
==============================================================================================================================

```

**Comment by matifali** [comment]
@prabhakk-mw I have noticed that `/bin/run.sh` is no longer available in `r2024a`. So how does one start the `-vnc` and `-browser` now? Thanks.

**Comment by matifali** [comment]
Yes I am building it from the Dockerfile

**Comment by prabhakk-mw** [comment]
> > Could it be that you are looking for run.sh in the r2024a image built from matlab-dockerfile ?
> 
> Yes. Could you link a Dockerfile that have everything?

@matifali , The Dockerfile that builds `mathworks/matlab` with the implementations is on the plan to be released in the near future.

Would you please create an issue requesting for the same?
I'd be happy to udpate that issue when the Dockerfile is released.

Thanks!
