### ISSUE TITLE
MATLAB Products not supported by MPM

### ISSUE THREAD

**Issue by nmerlene** [mathworks-ref-arch/matlab-dockerfile#47]
Hi,

I've been using the Dockerfile + MPM solution for a few months now and it works great, with the only exception being that there's a few products it doesn't seem to support yet:

```
#6 5.778 Installing with the following parameters:
#6 5.778 --destination=/opt/matlab
#6 5.778 --release=r2021b
#6 5.778 --products=MATLAB MATLAB_Coder DO_Qualification_Kit Simulink Simulink_Coder Simulink_Design_Verifier Simulink_Check Simulink_Test Simulink_Code_Inspector Simulink_Coverage
#6 5.778 ---------------------------------------------
#6 9.371 Error: Unable to install these products because they are not supported by MPM:
#6 9.371 DO_Qualification_Kit
#6 9.371 Simulink_Code_Inspector
```

Is there any plan (or would it be possible) to add support for the `DO Qualification Kit` and `Simulink Code Inspector` products in the near future?  My initial assumption was that MPM would be able to install any product *not* listed under [Products Not Available for Linux](https://www.mathworks.com/support/requirements/system-requirements-linux.html).

**Comment by cuixing158** [comment]
Hi, @nmerlene
Perhaps you could also install the toolbox via the Add-on plugin in the main matlab interface

**Comment by prabhakk-mw** [comment]
@drobinson0 thoughts ?

**Comment by prabhakk-mw** [comment]
https://github.com/mathworks-ref-arch/matlab-dockerfile/commit/30fb813e080c8163b1f12d28003b73d34ccf97c1 addresses this.
