### ISSUE TITLE
Release Dockerfile for MATLAB r2022b image.

### ISSUE THREAD

**Issue by matifali** [mathworks-ref-arch/matlab-dockerfile#49]

**Comment by josmartin** [comment]
@matifali The repo supports building R2022b - you just need to pass in the appropriate build argument for `MATLAB_RELEASE` as shown below.

```
$ git clone https://github.com/mathworks-ref-arch/matlab-dockerfile.git

$ cd matlab-dockerfile

$ docker build -t matlab:r2022b --build-arg MATLAB_RELEASE=r2022b .
Sending build context to Docker daemon  229.9kB
Step 1/13 : ARG MATLAB_RELEASE=r2022a
Step 2/13 : FROM mathworks/matlab-deps:${MATLAB_RELEASE}
 ---> 6c7b97f27ef3
Step 3/13 : ARG MATLAB_RELEASE
 ---> Running in 3e57fbaa9f4c
Removing intermediate container 3e57fbaa9f4c
...
```

**Comment by matifali** [comment]
No it does not work.
```
docker build -t matlab:r2022b --build-arg MATLAB_RELEASE=r2022b .
Sending build context to Docker daemon  112.1kB
Step 1/13 : ARG MATLAB_RELEASE=r2022a
Step 2/13 : FROM mathworks/matlab-deps:${MATLAB_RELEASE}
manifest for mathworks/matlab-deps:r2022b not found: manifest unknown: manifest unknown
```

**Comment by josmartin** [comment]
@matifali Apologies I had already built a `mathworks/matlab-deps:r2022b` image on the machine I ran the above on. We are currently targeting a release of `mathworks/matlab-deps:r2022b` in the next day or 2. I'll close this issue when we have released the base container.

**Comment by matifali** [comment]
No issue. Now it is released and I can build r2022b.

**Comment by prabhakk-mw** [comment]
@matifali As you might've noticed `mathworks/matlab-deps:r2022b` has been released, and should unblock you. 
I will close this issue shortly, when the `matlab-dockerfile` repository is updated to include support for R2022b.

Thank you.
