### ISSUE TITLE
Dockerfile does not work for r2022b

### ISSUE THREAD

**Issue by matifali** [mathworks-ref-arch/matlab-dockerfile#50]
No it does not work.
```
docker build -t matlab:r2022b --build-arg MATLAB_RELEASE=r2022b .
Sending build context to Docker daemon  112.1kB
Step 1/13 : ARG MATLAB_RELEASE=r2022a
Step 2/13 : FROM mathworks/matlab-deps:${MATLAB_RELEASE}
manifest for mathworks/matlab-deps:r2022b not found: manifest unknown: manifest unknown
```

_Originally posted by @matifali in https://github.com/mathworks-ref-arch/matlab-dockerfile/issues/49#issuecomment-1257256238_

**Comment by josmartin** [comment]
I've re-opened #49 - as mentioned there `mathworks/matlab-deps:r2022b` will be released soon - will close this issue so that we use #49 to track when the new release goes live.
