### ISSUE TITLE
MATLAB + Simulink Container taking forever to exit

### ISSUE THREAD

**Issue by AnasAGSO** [mathworks-ref-arch/matlab-dockerfile#56]
Hi and thank you for the help,
when i try to run a simple MATLAB + Simulink test model where i import data from an input.mat and create a new output.mat using "To File" Simulink block, everything works smoothly i get the result in the terminal and the file gets created but the container gets stuck and exits after ~6min (MATLAB only code exit instantly after returning results).
![image](https://user-images.githubusercontent.com/119883186/207093316-d12493af-89aa-4fc6-8b8e-5d15a95e98e6.png)
![image](https://user-images.githubusercontent.com/119883186/207092880-45024a76-6907-41f0-afbc-9ea55c562624.png)

**Comment by ggriffithsuk** [comment]
Hi @AnasAGSO, 
1) which `MATLAB-RELEASE` value are you setting when you build your image?
2) other than adding simulink to the `--products` list, have you made any other changes to the Dockerfile?
Thanks,
Gareth

**Comment by AnasAGSO** [comment]
thank you so much for the quick answer:
1- r2022b
2- No only Simulink manually installed on the  dockerhub mathworks/matlabcontainer 
`sudo ./mpm install --release=r2022b --destination=/opt/matlab/R2022b --products Simulink
`
and saved it as a new image

test files: https://github.com/AnasAGSO/matlab-hydro
dockerfile: is just from myNewImage nothing else

**Comment by ggriffithsuk** [comment]
> thank you so much for the quick answer: 1- r2022b 2- No only Simulink manually installed on the dockerhub mathworks/matlabcontainer `sudo ./mpm install --release=r2022b --destination=/opt/matlab/R2022b --products Simulink ` and saved it as a new image
> 
> test files: https://github.com/AnasAGSO/matlab-hydro dockerfile: is just from myNewImage nothing else

Hi @AnasAGSO,
Thanks for sharing your reproduction steps; we were able to reproduce the hang that you reported. We've [patched](https://github.com/mathworks/build-glibc-bz-19329-patch/blob/main/BZ-17645.md) the mathworks/matlab-deps and mathworks/matlab images on DockerHub, so if you rebuild your image the issue will hopefully be resolved for you. Please do let us know.
Thanks,
Gareth

**Comment by AnasAGSO** [comment]
Thank you @ggriffithsuk and all the mathworks & glibc team members, everything is working perfectly now.
