### ISSUE TITLE
Image built from Dockerfile doesn't work like the one provided on Docker Hub

### ISSUE THREAD

**Issue by Alexander-Wilms** [mathworks-ref-arch/matlab-dockerfile#57]
Since I wanted to build the Matlab image from source and make some modifications, I first wanted to reproduce the image available on Docker Hub.

However, if I follow the instructions but don't provide a license server address, I don't get prompted and the container shuts down immediately.

What am I missing?

```
alexander@PC:~/Development/matlab-dockerfile> docker build -t matlab:r2022b .
alexander@PC:~/Development/matlab-dockerfile> docker run -it --rm -p 8888:8888 --shm-size=512M matlab:r2022b
MATLAB is selecting SOFTWARE OPENGL rendering.
alexander@PC:~/Development/matlab-dockerfile> docker run -it --rm -p 8888:8888 --shm-size=512M mathworks/matlab:r2022b

Running matlab 
MATLAB is selecting SOFTWARE OPENGL rendering.
Please enter your MathWorks Account email address and press Enter:
```

**Comment by Alexander-Wilms** [comment]
Okay, I found [this](https://github.com/mathworks-ref-arch/matlab-dockerfile/issues/48#issuecomment-1218405878) comment saying that one needs [matlab-proxy](https://github.com/mathworks/matlab-proxy) as well. Now I'll have to figure out how to get it working.

Is the Dockerfile in this repo supposed to be more minimal or could you include matlab-proxy?

**Comment by Alexander-Wilms** [comment]
I got it to work using [this](https://github.com/mathworks/matlab-proxy/blob/main/examples/Dockerfile) Dockerfile. Maybe you could explain this in the README or make it accessible under https://hub.docker.com/r/mathworks/matlab/dockerfile (if that is actually the Dockerfile used for the `mathworks/matlab` image)

**Comment by prabhakk-mw** [comment]
> Okay, I found [this](https://github.com/mathworks-ref-arch/matlab-dockerfile/issues/48#issuecomment-1218405878) comment saying that one needs [matlab-proxy](https://github.com/mathworks/matlab-proxy) as well. Now I'll have to figure out how to get it working.
> 
> Is the Dockerfile in this repo supposed to be more minimal or could you include matlab-proxy?

@Alexander-Wilms yes it is possible for you to install `matlab-proxy` into the Dockerfile as listed in this repository.
You can use the example shown in the `matlab-proxy` repository to make the necessary changes.

The `mathworks/matlab` image listed on dockerhub does **not** have a publicly available Dockerfile yet. Currently it uses some bespoke infrastructure which we are working towards open sourcing soon.

Merging [matlab-dockerfile/Dockerfile](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/Dockerfile) with the  contents of the [matlab-proxy/examples/Dockerfile](https://github.com/mathworks/matlab-proxy/blob/main/examples/Dockerfile) is a reasonable approach if using the `-browser` option is all you want to replicate in your newly created container.

Please do let us know if you have any further questions or thoughts on the matter.
