### ISSUE TITLE
Problem with permissions for shared mounted files/folders in mathworks/matlab-deep-learning containers?

### ISSUE THREAD

**Issue by cuixing158** [mathworks-ref-arch/matlab-dockerfile#60]
I failed to build the container by the following command line method, how can I make the matlab-online container(`- browser`) have the same file/folder operation permissions as the host user(mount the shared folder)?
```bash
docker run -d --rm  --shm-size=512M -u <my-uid> -v $pwd:/matlab_works/ mathworks/matlab-deep-learning:r2022b -browser
```
where `<my-uid>` is my host computer uid.

 However, I can successfully build the container by specifying the ["matlab"](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/2d1325647decf1a2e54226c38da287f9efd583d1/Dockerfile#L69) user, but its uid(1000) is not the same as the host uid(1007), which leads to problems with file mount permissions. How can I resolve this?

**Comment by cuixing158** [comment]
When I use docker to switch to the root account `docker exec -it -u root  <my-matlab-container> bash` and then change the uid/gid for the "matlab" normal account to the same uid/gid as the host, i.e. execute `usermod -u 1007 matlab` and `groupmod -g 1007 matlab`, but the uid/gid is still not changed in the browser matlab environment(Execute `!id` on the matlab command line window to get the current user id, but it is still 1000), I still do not have the appropriate permissions to manipulate the m-file in the shared folder.

**Comment by prabhakk-mw** [comment]
@cuixing158 
This is a tricky problem, if you want to write to the mounted location. 
It seems like the docker ecosystem designed volumes as a means to load data into the container without actually writing into that location.

This has been discussed at length in the community at [moby/7198](https://github.com/moby/moby/issues/7198)

There are some valid flags raised in the conversation. For example, making modifications to the container to work in this way would break portability and one could argue make the system a little less secure.

Apart from the thread mentioned above, the following links also give some ideas:
1. https://stackoverflow.com/questions/23544282/what-is-the-best-way-to-manage-permissions-for-docker-shared-volumes
2. https://medium.com/@ramangupta/why-docker-data-containers-are-good-589b3c6c749e
3. https://github.com/moby/moby/issues/7198#issuecomment-73585113

Unfortunately, there isn't a standardized solution that I can recommend to you at this time.
Please let us know if there is more we can do to help.

Thank you!

**Comment by prabhakk-mw** [comment]
That said, It might be possible for you to build your own docker container image with a user that has the same UID and GUID as your local user? 

Could you try modifying the [Dockerfile](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/Dockerfile) in this repository to achieve that?

**Comment by prabhakk-mw** [comment]
Once you have that working, you can install the `-browser` functionality using the [matlab-proxy/examples/Dockerfile ](https://github.com/mathworks/matlab-proxy/blob/main/examples/Dockerfile) as a template.

Please let me know if you need help with that.

**Comment by josmartin** [comment]
Just to add / confirm what @cuixing158 suggests above - the third solution in the blog post above, in which a `Dockerfile` is used to build a container for a specific machine in which an appropriate user is created at build time is by far the best solution to this particular problem. The only additional thing someone may want to think about are any files inside the default users home folder that are needed to be copied to the newly created users home folder. In the `mathworks\matlab` containers case there aren't any - but in some arbitrary containers case you may need to consider this.

**Comment by prabhakk-mw** [comment]
Listed below is a Dockerfile with a version of the approach suggested above:

```Dockerfile
# Dockerfile to add users to existing mathworks containers

# Sample Docker build command: 
# docker build --build-arg USERNAME=`id -un` --build-arg UID=`id -u` --build-arg GID=`id -g` -t mathworks/matlab:localuser-r2022b  .

# Sample Docker run command:
# docker run --init -it --rm -p 8888:8888 mathworks/matlab:localuser-r2022b -browser

# Use lower case to specify the release, for example: ARG MATLAB_RELEASE=r2021b
ARG MATLAB_RELEASE=r2022b

# Adding user to existing container
# build time arguments to customize the user created in the container
ARG USERNAME=matlab
ARG UID=1000
ARG GID=1000

# When you start the build stage, this Dockerfile by default uses the Ubuntu-based matlab-deps image.
# To check the available matlab-deps images, see: https://hub.docker.com/r/mathworks/matlab-deps
FROM mathworks/matlab:${MATLAB_RELEASE}

# Declare the global argument to use at the current build stage
ARG MATLAB_RELEASE
ARG USERNAME
ARG UID
ARG GID

USER root

# Create local user with build-args 
RUN groupadd -g ${GID} -o ${USERNAME} \
    && useradd -m -u ${UID} -g ${GID} -o -s /bin/bash ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

# Copy files from default "matlab" user to new user
RUN cp -r /home/matlab/Documents /home/${USERNAME}/Documents \
    && chown -R ${UID}:${GID} /home/${USERNAME}/Documents

USER ${USERNAME}
WORKDIR /home/${USERNAME}/Documents/MATLAB/

```

**Comment by cuixing158** [comment]
good dockerfile example template! EXECELENT! @prabhakk-mw
