### ISSUE TITLE
Fixed one  brocked another

### ISSUE THREAD

**Issue by DanRRRR** [mathworks-ref-arch/matlab-dockerfile#68]
Hi
I see the documentation on front page is edited fixing the issue i reported with mpm vs ./mpm.
But it broke another  by missing destination directory due to which it now does not install at all.

As to not placing Matlab icon on Desktop for easy start - that is another pity part of this installation. To use terminal for program start is total anachronism. This is why no one will ever use Linux. Installation have to be just one click deal

**Comment by prabhakk-mw** [comment]
Hi @DanRRRR 

Could you please be more specific? 
Which line in particular is missing the destination directory?

As for the Icon, yes several linux based commands, softwares and packages do not come pre-configured to create icons.
This is a pain point for some users switching from a windows mindset to linux.

Please use the full MATLAB installer, that can be downloaded from `www.mathworks.com ` should, to include features like automatic Icon creation.

Also refer to this [blog post ](https://amalj07.medium.com/how-to-create-a-desktop-icon-on-ubuntu-or-debian-based-systems-333c82464683) for more information on how to add an icon.
