### ISSUE TITLE
Running MATLAB 2021a in a Singularity container on a CentOS 6.9 host.

### ISSUE THREAD

**Issue by natbutter** [mathworks-ref-arch/matlab-dockerfile#70]
Hi there, I am trying to modify the provided Dockerfile to then compile into a Singularity image and run on CentOS 6.9 HPC system.

To do this I must use a CentOS 7 base image (or Ubuntu 16.04), which balances the old host environment and the newer requirements of MATLAB.

Container builds fine and runs on my local Ubuntu 20.04 seamlessly. When moving to the HPC, the container seems to work, but then no MATLAB output is produced, like does not even launch. Best I can do (if I don't include `-nojvm` flags for example) is have the warning message appear in the terminal "MATLAB is selecting SOFTWARE OPENGL rendering." but then MATLAB just does not launch and I am returned to the shell. Other software in the image runs as expected.
The old operating system being the issue is just a hunch, but I can't even get an error to diagnose.

Before I dig around the `/opt/matlab/bin/matlab` launch script and put a bunch of `echo` outputs in there, any suggestions?

Thank you.

Not working on CentOS 6.9 host:
```
user@cento6$ singularity run matlab.img /bin/bash
Singularity> matlab
MATLAB is selecting SOFTWARE OPENGL rendering.
Singularity> matlab -nojvm -nodisplay -debug -nosplash
Singularity>
```

Working on Ubuntu 20.04:
```
user@ubuntu20$ singularity run matlab.img /bin/bash
Singularity> matlab -nojvm
MATLAB is selecting SOFTWARE OPENGL rendering.

                                                < M A T L A B (R) >
                                      Copyright 1984-2021 The MathWorks, Inc.
                                 R2021a Update 8 (9.10.0.2198249) 64-bit (glnxa64)
                                                 February 15, 2023

 
For online documentation, see https://www.mathworks.com/support
For product information, visit www.mathworks.com.
 
>> disp("hello world")
hello world
>> 
```

**Comment by prabhakk-mw** [comment]
Hi @natbutter 

Would you please share your version of the `Dockerfile` , along with the steps taken to launch the container?
It would become easier to assist you if we are able reproduce this behavior at our end.

If I had to guess, this issue is mostly likely due to missing system dependencies for MATLAB to run on Ubuntu 16.04 

Attached is a text file [base-dependencies.txt](https://github.com/mathworks-ref-arch/matlab-dockerfile/files/11403549/base-dependencies.txt) which contains a list of packages that need to be installed on Ubuntu 16.04 for R2021a.

Download this file into the folder containing your Dockerfile and include it as as show below:
```Dockerfile
COPY base-dependencies.txt /tmp/base-dependencies.txt

RUN apt-get update && apt-get install --no-install-recommends -y `cat /tmp/base-dependencies.txt` \
    && apt-get clean && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*
```

Please re-open this issue along with the requested information if this updating the dependencies does not resolve the issue.

Thank you!

**Comment by natbutter** [comment]
Thank you for the response.

Unfortunately I believe the issue is because the Host OS is simply too old. Specifically, it is missing the system call `getrandom`.

Running a trace on Matlab while launching with:
```
strace -c /opt/matlab/bin/glnxa64/MATLAB -nodisp -nojvm -prefersoftwareopengl
```

I could see there were errors associated with the `getrandom` system calls, producing 3 errors like this:
```
getrandom(0x10faf80, 32, 0)             = -1 ENOSYS (Function not implemented)
```

There may be some hack to get this system call inside the container.... but not quite sure what that would look like just yet.


This is the Dockerfile FYI (working on newer host systems, but not with old glibc):
```
FROM ubuntu:16.04

COPY base-dependencies.txt /tmp/base-dependencies.txt

RUN apt-get update && apt-get install --no-install-recommends -y `cat /tmp/base-dependencies.txt` \
    && apt-get clean && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install --no-install-recommends --yes \
    wget \
    unzip \
    ca-certificates \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

ARG MATLAB_RELEASE=r2021a
ARG MATLAB_RELEASE

RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \
    && chmod +x mpm \
    && ./mpm install \
    --release=${MATLAB_RELEASE} \
    --destination=/opt/matlab \
    --products MATLAB \
    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) \
    && rm -f mpm /tmp/mathworks_root.log \
    && ln -s /opt/matlab/bin/matlab /usr/local/bin/matlab

COPY network.lic /opt/matlab/licenses/
```
