### ISSUE TITLE
Alternative for unsupported Products and Support Packages

### ISSUE THREAD

**Issue by gamlab-jlin** [mathworks-ref-arch/matlab-dockerfile#78]
Hello,

I found the latest update (2023.10.0.1 - October 26, 2023) quite helpful for workflows such as CI.
Especially, the newly introduced feature which allows the installation of hardware and software support packages and the installer input file.

I believe it would be beneficial to mention in the ReadMe the alternatives for the limitations of MPM.
For example the use of MATLAB installer with FIK and the use of the Support Software Downloader as mentioned below.
For the latter, it would also be beneficial to update the documentation of the Support Package: _CI/CD Automation for Simulink Check_, as this relies on the Docker workflow and MPM. This update could improve the experience of the Support Package and standardize the Dockerfiles.

How do I download and install a support package on an offline machine?
https://www.mathworks.com/matlabcentral/answers/293235-how-do-i-download-and-install-a-support-package-on-an-offline-machine

Download Hardware Support Packages and Optional Features
https://www.mathworks.com/support/install/support-software-downloader.html

**Comment by michaelmcdonnellmw** [comment]
Hi @gamlab-jlin,

Thanks for reaching out to us about this, you make some very sensible suggestions. 

We will discuss this internally and determine the most appropriate location to include any additional information, along with any updates required for the documentation of the support package you highlighted. Once we have done this we will update our documentation accordingly.
