### ISSUE TITLE
Unable to install ".mlpkginstall" file in web browser mode

### ISSUE THREAD

**Issue by cuixing158** [mathworks-ref-arch/matlab-dockerfile#81]
I have successfully built and run my MATLAB browser mode container according to the steps in this repo back in the first half of this year(#59,#60,#61), and everything seems to be working fine, but in MATLAB in browser I can't install the official file [vgg16.mlpkginstall](https://www.mathworks.cn/matlabcentral/fileexchange/61733-deep-learning-toolbox-model-for-vgg-16-network) from File Exchange, and the other files are similarly uninstallable.  I have tried the following 2 methods, but they still don't work, how can I solve this?

- Find and install through the "Add-on" plugin in the main interface. but I couldn't open the "Add-on" interface. #59
![1](https://github.com/mathworks-ref-arch/matlab-dockerfile/assets/22857777/102ed6b0-d8b2-4c29-8b93-58e45cdb31a6)

- Tried to download the ".mlpkginstall" file from File Exchange, then copied it to the current working folder in the container, and double-clicked on the ".mlpkginstall" file to install it, but it crashed and quit directly. MATLAB crashes and exits.
![2](https://github.com/mathworks-ref-arch/matlab-dockerfile/assets/22857777/6db9b17a-6c94-480b-9e07-fce5183a48a8)

Version used: Matlab R2023a

**Comment by prabhakk-mw** [comment]
Hi @cuixing158 

Thank you for reporting this.
There might be third way that you could explore?

`MPM` recently released the capability to install support packages. See: [MPM.md](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/MPM.md#20231001---october-26-2023)

We have also released a list of input files that can be used to reference the product & support packages by MATLAB release. This is the [file for R2023a](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/mpm-input-files/R2023a/mpm_input_r2023a.txt).

It does list the VGG16 & VGG19 packages there, could you try using this ?

Finally, seeing MATLAB crash is never something we like to see.
Could you share more information about how we could reproduce this?
We would need:
1. The Dockerfile that was used, and the command used to build it. 
2. The Docker run command used to start the container.
3. The commands/steps used to download and include the file into the MATLAB installation.
4. The steps you took within MATLAB to get it to crash.
5. The crash logs that you have already accumulated. They can either be recovered from the UI you have shown above, or from the file system. For example: `find *crash_dump* ~/.matlab/MWI`

**Comment by cuixing158** [comment]
Thanks for your latest update to the [MPM.md](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/MPM.md#changelog) documentation recently, especially the addition of the inputfile file to the input, which is much more convenient than before. I haven't had a chance to try out your latest usage yet though, I'll use it up sometime in the future! The container I'm currently using is still from a build earlier this year, and some of the commands can be found in my question #59 .

My solution for now is to use the desktop version of MATLAB directly, and when I have time to follow I'll build and run the containers in the same way as I specified the inputfile.

Thanks again for your detailed answer!
