### ISSUE TITLE
Install products as a user on an HPC?

### ISSUE THREAD

**Issue by SerenaCaplins** [mathworks-ref-arch/matlab-dockerfile#82]
Is it possible to use mpm to install just the products I want to add to an HPC (where I don't have root permissions on the matlab directories)?

Telling it to use my directories has resulted in it installing matlab along with the products I needed. I need to use the system wide installation of matlab because it runs via an Open on Demand app. 

Thank you!

**Comment by philipc-mw** [comment]
Hi SerenaCaplins,

Thank you for your question! Just to gather a little more information, what kind of products are you interested in installing? In particular, are you interested in installing toolboxes, support packages, or both?

Thanks,
Philip

**Comment by philipc-mw** [comment]
Hi Serena,

Thank you for the info. The product you wish to install is a support package. The exact steps required to install this support package will depend on the configuration of your HPC system, including whether the worker nodes have access to the installation destination for support packages (the support package root). The admin of the HPC system should be able to provide guidance on this. You can determine the support package root by running the MATLAB command [matlabshared.supportpkg.getSupportPackageRoot](https://www.mathworks.com/help/matlab/ref/matlabshared.supportpkg.getsupportpackageroot.html).

Toolboxes will definitely need root permissions, and so for those you will need to make a request to the admin of your HPC system. Can you make a request to the admin of the HPC system to install these toolboxes and support packages on your system?

Thanks,
Philip

**Comment by prabhakk-mw** [comment]
@SerenaCaplins I'm closing this issue as we haven't heard back from you in a while, please do let us know if you need any more assistance with this issue to re-open it.
