### ISSUE TITLE
FMU Builder For Simulink Support package not installed?

### ISSUE THREAD

**Issue by fmg-kevin-kilroy** [mathworks-ref-arch/matlab-dockerfile#83]
I'm trying to use the FMU_Builder_For_Simulink support package and the latest r2023b release. I have added it to the list of products to install. However, when I try to build my model using the built image, I get the following error message:

```
FMU export requires FMU Builder for Simulink support package. To install this
support package, use the <a
href="matlab:matlab.internal.addons.launchers.showExplorer('tripwire','identifier','FMUBUILDER');">Add-On
Explorer</a>
```

I noticed in the logs during the building of the image:

```
The following MathWorks Support Packages are licensed under the MathWorks Auxiliary Software License
Agreement, available in the installation of the MathWorks Support Packages or in the virtual
machine image.
FMU_Builder_For_Simulink

Products will be installed to: /opt/matlab/r2023b
Starting install...
Support packages will be installed to: /root/Documents/MATLAB/SupportPackages/R2023b
Finished install
Completing setup...
Installation complete
```

I had a look inside the built image and /root/Documents/MATLAB/SupportPackages/R2023b doesn't exist.

This is the step in the Dockerfile that does the install via mpm:

`RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm     && chmod +x mpm     && ./mpm install     --release=r2023b     --destination=/opt/matlab/r2023b     --products Parallel_Computing_Toolbox Simulink FMU_Builder_For_Simulink SimBiology Statistics_and_Machine_Learning_Toolbox DSP_System_Toolbox DSP_HDL_Toolbox DDS_Blockset Embedded_Coder Signal_Processing_Toolbox     || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false)     && rm -f mpm /tmp/mathworks_root.log     && ln -s /opt/matlab/r2023b/bin/matlab /usr/local/bin/matlab`

**Comment by fmg-kevin-kilroy** [comment]
I ran the command:

`matlabshared.supportpkg.getInstalled`

And the result was: 

`No support packages installed. To install support packages, open <a href="matlab: matlab.addons.supportpackage.internal.explorer.showAllHardwareSupportPackages('supportPackageInstaller');">Add-On Explorer</a>`

**Comment by fmg-kevin-kilroy** [comment]
I've tried to use this tool:

https://au.mathworks.com/support/install/support-software-downloader.html

but get this error:

```
/opt/matlab/r2023b/bin/glnxa64/SupportSoftwareInstaller -downloadfolder /root/Documents/MATLAB/SupportPackages/R2023b/ -inputfile /root/Documents/MATLAB/SupportPackages/R2023b/ssi_input.txt
terminate called after throwing an instance of 'std::invalid_argument'
  what():  BAD KEY VALUE, no '-' prefix: "/root/Documents/MATLAB/SupportPackages/R2023b/"
Aborted
```

**Comment by prabhakk-mw** [comment]
Hi @fmg-kevin-kilroy 
We've updated the Dockerfile to install MATLAB using MPM as the user `matlab`.
This ensures that MATLAB itself continues to be installed where it used to previously. viz: in a globally accessible read-only location, where as it installs the support packages into the `matlab` user's home folder.

Please let us know if this approach enables your workflows.

Thank you!

**Comment by fmg-kevin-kilroy** [comment]
Hi @prabhakk-mw .
I've tried the new Dockerfile but the support package is still not installed when I add it to the product list during the matlab install. 

Do I need to use the https://au.mathworks.com/support/install/support-software-downloader.html to install it separately? If so when I try I get the following error:

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  BAD KEY VALUE, no '-' prefix: "/home/matlab/MATLAB/SupportPackages/R2023b/"
Aborted
```

The Support package I'm trying to install is: FMU_Builder_For_Simulink.

Thanks

**Comment by fmg-kevin-kilroy** [comment]
The install logs do seem to suggest that it will be installed. Do I need to make the /home/matlab/MATLAB/SupportPackages/R2023b/ prior to kicking off the install?

```
[5/6] RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm     && chmod +x mpm     && sudo HOME=${HOME} ./mpm install     --release=r2023b     --destination=/opt/matlab/     --products Parallel_Computing_Toolbox Simulink FMU_Builder_For_Simulink SimBiology Statistics_and_Machine_Learning_Toolbox DSP_System_Toolbox DSP_HDL_Toolbox DDS_Blockset Embedded_Coder Signal_Processing_Toolbox     || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false)     && sudo rm -f mpm /tmp/mathworks_root.log     && sudo ln -s /opt/matlab/bin/matlab /usr/local/bin/matlab
62.83 Installing with the following parameters:
62.83 --destination=/opt/matlab
62.83 --doc=false
62.83 --release=R2023b
62.83 --products=Parallel_Computing_Toolbox, Simulink, **FMU_Builder_For_Simulink**, SimBiology, Statistics_and_Machine_Learning_Toolbox, DSP_System_Toolbox, DSP_HDL_Toolbox, DDS_Blockset, Embedded_Coder, Signal_Processing_Toolbox
62.83 ---------------------------------------------
72.66 The following required products will also be installed:
72.66 MATLAB
72.66 Simulink
72.66 Fixed-Point Designer
72.66 MATLAB Coder
72.66 MATLAB Compiler
72.66 Simulink Compiler
72.66 
72.66 The following MathWorks Products are licensed under the The MathWorks, Inc. Software License
72.66 Agreement, available in the installation of the MathWorks Product or in the virtual machine image.
72.66 MATLAB_Compiler, DDS_Blockset, Parallel_Computing_Toolbox, DSP_System_Toolbox, Embedded_Coder, DSP_HDL_Toolbox, MATLAB_Coder, MATLAB, Fixed-Point_Designer, SimBiology, Signal_Processing_Toolbox, Simulink_Compiler, Simulink, Statistics_and_Machine_Learning_Toolbox
72.66 
72.66 The following MathWorks Support Packages are licensed under the MathWorks Auxiliary Software License
72.66 Agreement, available in the installation of the MathWorks Support Packages or in the virtual
72.66 machine image.
72.66 **FMU_Builder_For_Simulink**
72.66 
72.66 Products will be installed to: /opt/matlab
73.26 Starting install...
1636.4 Support packages will be installed to: /home/matlab/Documents/MATLAB/SupportPackages/R2023b
1637.7 Finished install
1638.0 Completing setup...
1643.7 Installation complete
```

**Comment by prabhakk-mw** [comment]
Hi @fmg-kevin-kilroy 

I've verified that the latest Dockerfile works for the set of products that you have listed.
I built the image using the following command:

```
$ docker build --build-arg MATLAB_PRODUCT_LIST="MATLAB Parallel_Computing_Toolbox Simulink FMU_Builder_For_Simulink SimBiology Statistics_and_Machine_Learning_Toolbox DSP_System_Toolbox DSP_HDL_Toolbox DDS_Blockset Embedded_Coder Signal_Processing_Toolbox"  -t matlab-dockerfile:83-soln https://raw.githubusercontent.com/mathworks-ref-arch/matlab-dockerfile/main/Dockerfile
```

And then run it using:

```
$ docker run -it --rm  matlab-dockerfile:83-soln

MATLAB is selecting SOFTWARE OPENGL rendering.

                                       < M A T L A B (R) >
                             Copyright 1984-2023 The MathWorks, Inc.
                        R2023b Update 5 (23.2.0.2459199) 64-bit (glnxa64)
                                        November 28, 2023

 
To get started, type doc.
For product information, visit www.mathworks.com.
 
>> matlabshared.supportpkg.getInstalled
          Name           Version Base Product
------------------------ ------- ------------
FMU Builder For Simulink 23.2.0
>> ver
-----------------------------------------------------------------------------------------------------
MATLAB Version: 23.2.0.2459199 (R2023b) Update 5
MATLAB License Number: DEMO
Operating System: Linux 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 23.2        (R2023b)
Simulink                                              Version 23.2        (R2023b)
DDS Blockset                                          Version 23.2        (R2023b)
DSP HDL Toolbox                                       Version 23.2        (R2023b)
DSP System Toolbox                                    Version 23.2        (R2023b)
Embedded Coder                                        Version 23.2        (R2023b)
Fixed-Point Designer                                  Version 23.2        (R2023b)
MATLAB Coder                                          Version 23.2        (R2023b)
MATLAB Compiler                                       Version 23.2        (R2023b)
Parallel Computing Toolbox                            Version 23.2        (R2023b)
Signal Processing Toolbox                             Version 23.2        (R2023b)
SimBiology                                            Version 23.2        (R2023b)
Simulink Compiler                                     Version 23.2        (R2023b)
Statistics and Machine Learning Toolbox               Version 23.2        (R2023b)
>> 

```

Could you please try this on your end ?

**Comment by fmg-kevin-kilroy** [comment]
When I run the actual code I still get this error:

```
Error using SetUpBalancingEffortFMU
FMU export requires FMU Builder for Simulink support package. To install this
support package, use the <a
href="matlab:matlab.internal.addons.launchers.showExplorer('tripwire','identifier','FMUBUILDER');">Add-On
Explorer</a>.
```

It is worth mentioning that I am using the matlab-batch helper command to pass in the token to run Matlab, so my dockerfile has this additional entry:

```
# ENTRYPOINT ["matlab"]
# CMD [""]
RUN sudo -E wget -qO- --retry-connrefused https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v0/install.sh | sudo -E bash -s

```

**Comment by prabhakk-mw** [comment]
@ggriffithsuk , could you take a look at this?

**Comment by prabhakk-mw** [comment]
@fmg-kevin-kilroy 

1. Does the code that is erroring out work as expected when run through MATLAB instead of MATLAB-BATCH in the container?  This will help us narrow down whether its the usage of MATLAB-BATCH that causes the issue.

2. Would you please share a code snippet to reproduce the error on our end?

Thank you.

**Comment by fmg-kevin-kilroy** [comment]
1. Yes the code does run as expected when we use the **matlab-actions/setup-matlab@v2-beta** and **matlab-actions/run-command@v1** Github Actions.
2. I will try to create a minimal example to show the issue.

**Comment by fmg-kevin-kilroy** [comment]
Using your Dockerfile, comment out the Entrypoint & CMD commands and add in the installation of matlab-batch:

```
# ENTRYPOINT ["matlab"]
# CMD [""]
RUN sudo -E wget -qO- --retry-connrefused https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v0/install.sh | sudo -E bash -s

```

Use the following Github Action Workflow to build and run the container. This requires a matlab-batch token to be stored as a secret in the Repo that is hosting the Dockerfile:

```
name: Build Matlab Docker Image using GHCR
on:
  workflow_dispatch:   

jobs:
  my-job:
    name: Build Matlab Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          build-args: |
              MATLAB_PRODUCT_LIST=Parallel_Computing_Toolbox FMU_Builder_For_Simulink 
          file: Dockerfile-MATLAB
          push: true
          tags: ghcr.io/${{ github.repository }}/matlab:2023b
          platforms: linux/amd64

      - name: Run Matlab Container
        run: docker run -v $GITHUB_WORKSPACE:/home/matlab/ -e MATHWORKS_TOKEN='${{ secrets.MATHWORKS_TOKEN }}' -e MATHWORKS_ACCOUNT='${{ secrets.MATHWORKS_ACCOUNT }}' ghcr.io/${{ github.repository }}/matlab:2023b sudo -E matlab-batch 'matlabshared.supportpkg.getInstalled'
      

```


Then you'll see:

`No support packages installed. To install support packages, open <a href="matlab: matlab.addons.supportpackage.internal.explorer.showAllHardwareSupportPackages('supportPackageInstaller');">Add-On Explorer</a>.`


It feels like to me that it's something to do with using sudo. Maybe the USER env var is used somewhere when constructing the path and it's picking up root rather than matlab

**Comment by michaelmcdonnellmw** [comment]
Hi @fmg-kevin-kilroy,
 
One thing I can see in your workflow example is that when you run the container you have a mount argument `-v $GITHUB_WORKSPACE:/home/matlab/`. What this will do is replace your entire home directory in the container with the contents of the github worspace. As support packages are installed under `/home/matlab/Documents/MATLAB/R2023b/` this will be removed in the example you have provided which is why the support package cannot be found.
 
You could instead mount the workspace in a new sub folder of the home directory (e.g. `-v $GITHUB_WORKSPACE:/home/matlab/github-workspace`) that should avoid this issue.
 
Can you give this a try and let us know if this solves your issue?
 
Thanks

**Comment by fmg-kevin-kilroy** [comment]
Doh! Yes!! that was it. Thanks for the help everyone.
