### ISSUE TITLE
It does not build on Docker on Mac

### ISSUE THREAD

**Issue by rragundez** [mathworks-ref-arch/matlab-dockerfile#85]
I run docker build --platform linux/amd64  -t matlab .

and I get the error

RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm     && chmod +x mpm     && sudo HOME=${HOME} ./mpm install     --release=r2023b     --destination=/opt/matlab/r2023b     --products MATLAB     || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false)     && sudo rm -f mpm /tmp/mathworks_root.log     && sudo ln -s /opt/matlab/r2023b/bin/matlab /usr/local/bin/matlab:
4.366 /tmp/mathworks_10/./bin/glnxa64/mpm: error while loading shared libraries: libCppMicroServices.so.3.7.6: cannot enable executable stack as shared object requires: Invalid argument
4.519 MPM Installation Failure. See below for more information:
4.532 cat: /tmp/mathworks_root.log: No such file or directory

**Comment by michaelmcdonnellmw** [comment]
Hi @rragundez,

Thanks for reporting this issue.

Is it possible to share some details of the Dockerfile you are using, i.e. are you directly using the Dockerfile present in this repository or are you using a custom / modified version?

Other users have also experienced issues with MATLAB using `libCppMicroServices` in the past and there is a solution to their issue here which may be of use: https://uk.mathworks.com/matlabcentral/answers/883849-permission-denied-while-loading-shared-libraries-in-matlab-installation-on-rh7

**Comment by rragundez** [comment]
Hi @michaelmcdonnellmw, I appreciate your prompt response. I found the problem but I will fully check tomorrow.

Seems to be a problem with the emulation via the Rosetta accelerator in Docker desktop, it can be deactivated in the settings of the Docker desktop UI.

**Comment by rragundez** [comment]
Hi @hassec no I didn't not found the real fix. Since we are deploying in a Linux based VM all works fine, we use this fix only for local testing in our MacBooks.
