### ISSUE TITLE
Unable to install files on my R2019b

### ISSUE THREAD

**Issue by MilesLucas14** [mathworks-ref-arch/matlab-dockerfile#86]
So I'm trying to run mpm command and here's the command I'm running:

`mpm install --inputfile "C:\Users\vaidi\Downloads\mpm_input_r2019b.txt"`

I'm running the Powershell on Admin mode, also changed the directory to the Directory of Matlab 2019b, yet it gives me this error:

WARNING: Uninstalling these products is not supported. To cancel this installation, press CTRL+C.

```
Installing with the following parameters:
--destination=C:\Program Files\MATLAB\R2019b
--doc=false
--no-gpu=false
--release=R2019b
--products=MATLAB Support for MinGW-w64 C/C++ Compiler, Simulink Coder Support Package for STMicroelectronics Nucleo Boards
---------------------------------------------
Error: No candidate available to install. mpm does not support release version: R2019b
```

Any suggestions on why it would do this? it worked perfectly on my R2023a. (I'm running R2019b for a specific product made to run on R2019b)

**Comment by michaelmcdonnellmw** [comment]
Hi @MilesLucas14,

Thanks for reaching out to us about this. While I look into this it would be helpful if you could provide some details about how you have modified the installer input file. Specifically have you changed any lines except the install location and the two support packages in the question?

Additionally would you be able to confirm the version of mpm you are running? You can find this by running `mpm -version`.

Finally, are you able to ping dws.mathworks.com?

**Comment by MilesLucas14** [comment]
Apologies for the delayed reply. 

No, other than the directory change, and the product uncomments, I have not changed anything in the input file. 

My current MPM version
`MATLAB Package Manager 2023.12.1 (win64)`

I apologise but I don't know what you mean by 'able to ping dws.mathworks.com?' I'm still in my learning phase, so please forgive me.

**Comment by michaelmcdonnellmw** [comment]
Hi @MilesLucas14,

No need to appologise.

To run the ping command open up which ever terminal you are using to run mpm (either command prompt or Powershell) and enter the command:

`ping dws.mathworks.com`

Ideally you should see a response that looks like:


```
Pinging e6779.b.akamaiedge.net [104.97.155.134] with 32 bytes of data:
Reply from 104.97.155.134: bytes=32 time=8ms TTL=56
Reply from 104.97.155.134: bytes=32 time=11ms TTL=56
Reply from 104.97.155.134: bytes=32 time=18ms TTL=56
Reply from 104.97.155.134: bytes=32 time=7ms TTL=56

Ping statistics for 104.97.155.134:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 7ms, Maximum = 18ms, Average = 11ms
```

If this is successful could you try rerunning the install to see if the issue was due to a temporary outage?

**Comment by MilesLucas14** [comment]
Yeah it does ping, yet it doesn't let me install it :(

**Comment by MilesLucas14** [comment]
Another thing I'd like to mention is,

When I change the directory to "C:\Program Files\MATLAB" then it does infact start downloading the files? But all the files are outside, instead of being inside the R2019b folder

**Comment by michaelmcdonnellmw** [comment]
Hi @MilesLucas14,

I apologies for the delay in getting back to, to confirm is this for a fresh install of MATLAB or do you already have an existing version installed in the R2019 Folder?

To give us a bit more information it might be helpful to see the installation logs from mpm, which can be found here: `%TEMP%\mathworks_%USERNAME%.log`.

Before sending them over it is worth taking a copy of the logs and then deleting the file before running a new install as that will give us the cleanest logs.

Before posting any logs make sure to remove any private information (such as your username) from the logs.

**Comment by prabhakk-mw** [comment]
@MilesLucas14  I'm closing this issue as we haven't heard back from you in a while, please do let us know if you need any more assistance with this issue to re-open it.
