### ISSUE TITLE
mpm input files for R2018b and earlier

### ISSUE THREAD

**Issue by davidtopham** [mathworks-ref-arch/matlab-dockerfile#87]
It would be useful to have example mpm input files for MATLAB versions R2018b and earlier. R2019a is currently the earliest in this repo, but the mpm documentation states that R2017b or later is supported.

I tried taking a copy of the R2019a one, but I assume I need to know the checksum to use at the end of the file.

**Comment by mw-wtripp** [comment]
Thanks, @davidtopham, for reaching out about this. Just to get more details about your scenario, which MATLAB releases before R2019a were you looking to install using mpm input files? Were you planning to install products, support packages, or both?

**Comment by davidtopham** [comment]
R2017b and R2018b, just products - the documentation [here ](https://github.com/mclarenapplied/cadevops-ansible)suggests it's already possible, I think I just need an mpm input file example.

We don't need support packages for these older versions.

**Comment by davidtopham** [comment]
Hi @mw-wtripp, any updates on this? I'm just after mpm-input-files for R2017b and R2018b.

**Comment by mw-wtripp** [comment]
Hi, @davidtopham. Apologies for the late reply. I double-checked with the team, and we should have the R2017b and R2018b input file posted by the end of March. I will let you know when they are available or if those plans change.

**Comment by davidtopham** [comment]
Thanks @prabhakk-mw and @mw-wtripp!
