### ISSUE TITLE
installation using MPM hangs

### ISSUE THREAD

**Issue by ondrejtichacek** [mathworks-ref-arch/matlab-dockerfile#89]
I am trying to install MATLAB using MPM in a Linux machine (running Arch linux).

The installation starts normally, downloads the products, installs something (totaling 3.6 GB) into the specified installation directory (user-owned), then hangs indefinitely. I tried to specify install options both via command line parameters and mpm input file - same result.

I don't see any log and/or option to increase verbosity to understand what is happening. Am I missing something?

Thanks!

Install log:

```
$ ./mpm install --inputfile ~/Box/MATLAB/mpm_input_r2023b.txt
Installing with the following parameters:
--destination=/home/ondrej/soft/matlab/R2023b
--doc=false
--no-gpu=false
--release=R2023b
--products=MATLAB, Optimization Toolbox, Parallel Computing Toolbox, Signal Processing Toolbox, Statistics and Machine Learning Toolbox
---------------------------------------------
The following MathWorks Products are licensed under the The MathWorks, Inc. Software License
Agreement, available in the installation of the MathWorks Product or in the virtual machine image.
Parallel_Computing_Toolbox, MATLAB, Optimization_Toolbox, Signal_Processing_Toolbox, Statistics_and_Machine_Learning_Toolbox

Products will be installed to: /home/ondrej/soft/matlab/R2023b
Starting install...
```

**Comment by prabhakk-mw** [comment]
@ondrejtichacek  I'm closing this issue as we haven't heard back from you in a while, please do let us know if you need any more assistance with this issue to re-open it.
