### ISSUE TITLE
Cannot install matlab2020a

### ISSUE THREAD

**Issue by antonlindahlcevt** [mathworks-ref-arch/matlab-dockerfile#9]
I have tried to build the image for matlab2020a but get the following error:

The command '/bin/sh -c cd /matlab-install && ./install -mode silent -inputFile /matlab_installer_input.txt' returned a non-zero code: 1

it works for matlab2018b and doing interactive in the crashed image i can run the exact same command and it succeeds.

**Comment by josmartin** [comment]
Just to confirm - have you updated the FIK in the matlab_installer_input.txt file since FIK's are version dependent?

**Comment by antonlindahlcevt** [comment]
No, that is probably not correct. However it feels super odd that I get an error code 1 from that and also that it works if I am in the container.

**Comment by josmartin** [comment]
For 2020a you will find that replacing lines 137 & 138 with the below should print out more info about the install and help you debug why it is failing. Could you try this and let us know what happens.

```
# Now install MATLAB
RUN cd /matlab-install \
    && ./install -mode silent -inputFile /matlab_installer_input.txt -outputFile /tmp/mlinstall.log \
    ; EXIT=$? && cat /tmp/mlinstall.log && test $EXIT -eq 0
```

**Comment by antonlindahlcevt** [comment]
Yeah so its the key that is incorrect. Maybe this could be the standard in the dockerfile?

(Apr 17, 2020 05:04:36) Reading from /matlab-install/archives
(Apr 17, 2020 05:04:36) Starting local product/component search in download directory
(Apr 17, 2020 05:04:36) Searching for archives...
(Apr 17, 2020 05:04:36) Reading /matlab-install/archives
(Apr 17, 2020 05:04:36) 2 files found in /matlab-install/archives
(Apr 17, 2020 05:04:36) Archive search complete.  2 total files found.
(Apr 17, 2020 05:04:36) Not a valid key for this release
(Apr 17, 2020 05:04:36) Exiting with status -2
(Apr 17, 2020 05:04:36) End - Unsuccessful
The command '/bin/sh -c cd /matlab-install     && ./install -mode silent -inputFile /matlab_installer_input.txt -outputFile /tmp/mlinstall.log     ; EXIT=$? && cat /tmp/mlinstall.log && test $EXIT -eq 0' returned a non-zero code: 1

Thanks for the quick responses!

**Comment by josmartin** [comment]
I do plan on making this change to the Dockerfile. Glad it worked out.
