### ISSUE TITLE
Add support for ARM architecture

### ISSUE THREAD

**Issue by BizarrePenguin** [mathworks-ref-arch/matlab-dockerfile#99]
I am using a MacBook Air with M1 processor and was already disappointed to see that no prebuilt docker images for matlab were available on mathworks/matlab-deps on DockerHub.

Now I tried to use this repo to build the image myself and it fails because the matlab dependency images that the Dockerfile in this repo is based on are also only available for amd64.

Would it be possible to add the matlab-deps for ARM and maybe even the fully functional matlab images?
Is there a good workaround besides completely writing a Dockerfile from scratch for ARM?

**Comment by BizarrePenguin** [comment]
At least I think this was the cause of my build failure.
Here is the cli output of my build attempt for reference:

```
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 4.38kB                                     0.0s
 => ERROR [internal] load metadata for docker.io/mathworks/matlab-deps:r2  1.4s
------
 > [internal] load metadata for docker.io/mathworks/matlab-deps:r2024a:
------
Dockerfile:28
--------------------
  26 |     # When you start the build stage, this Dockerfile by default uses the Ubuntu-based matlab-deps image.
  27 |     # To check the available matlab-deps images, see: https://hub.docker.com/r/mathworks/matlab-deps
  28 | >>> FROM mathworks/matlab-deps:${MATLAB_RELEASE}
  29 |     
  30 |     # Declare build arguments to use at the current build stage.
--------------------
ERROR: failed to solve: mathworks/matlab-deps:r2024a: no match for platform in manifest: not found

```

**Comment by versionbayjc** [comment]
I don't think this will work for arm64, since MATLAB (currently) only supports arm64 on macOS. For Linux (which your docker containers will most likely be based on...) the MATLAB System Requirements specify that you need an x86-64 arch, compare processor info for:
macOS: https://www.mathworks.com/support/requirements/matlab-mac.html
Linux: https://www.mathworks.com/support/requirements/matlab-linux.html
